import { email } from "questpie/services";
import { z } from "zod";

/**
 * Minimal HTML-entity escape for values interpolated into the email markup.
 *
 * `name` is supplied by the visitor at sign-up, so it is untrusted and could
 * carry markup. `verifyUrl` is generated by Better Auth, but it lands in an
 * `href` attribute, so it is escaped too (defense-in-depth against a crafted
 * callback URL). The plain-text body below uses the raw values on purpose —
 * there is no markup context there to break out of.
 */
function escapeHtml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#39;");
}

/**
 * Account e-mail verification message (Slovak product copy).
 *
 * Sent by the Better Auth `emailVerification.sendVerificationEmail` hook wired
 * in `config/auth.ts`. In development the console mail adapter logs the
 * plain-text body, so the raw verify link is visible in the dev-server output
 * — that is the human-testable onboarding path.
 */
export default email({
	name: "verify-email",
	schema: z.object({
		verifyUrl: z.string().url(),
		name: z.string(),
	}),
	handler: ({ input }) => {
		const safeName = escapeHtml(input.name);
		const safeUrl = escapeHtml(input.verifyUrl);
		return {
			subject: "Overte svoj e-mail — QUESTPIE Autopilot",
			html: `
				<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; max-width: 560px; margin: 0 auto; padding: 32px 24px; color: #1c1917;">
					<p style="font-size: 13px; letter-spacing: 0.08em; text-transform: uppercase; color: #a93b29; font-weight: 700; margin: 0 0 20px;">QUESTPIE Autopilot</p>
					<h1 style="font-size: 22px; line-height: 1.3; margin: 0 0 12px;">Overte svoj e-mail</h1>
					<p style="color: #57534e; font-size: 15px; line-height: 1.6; margin: 0 0 24px;">
						Dobrý deň ${safeName}, ďakujeme za registráciu. Pre aktiváciu účtu potvrďte svoju e-mailovú adresu.
					</p>
					<a href="${safeUrl}" style="display: inline-block; background: #a93b29; color: #ffffff; text-decoration: none; font-weight: 600; font-size: 15px; padding: 12px 24px; border-radius: 10px;">
						Overiť e-mail
					</a>
					<p style="color: #78716c; font-size: 13px; line-height: 1.6; margin: 28px 0 0;">
						Ak tlačidlo nefunguje, skopírujte tento odkaz do prehliadača:<br />
						<a href="${safeUrl}" style="color: #a93b29; word-break: break-all;">${safeUrl}</a>
					</p>
					<hr style="margin: 32px 0 16px; border: none; border-top: 1px solid #e7e5e4;" />
					<p style="font-size: 12px; color: #a8a29e; line-height: 1.6; margin: 0;">
						Ak ste si účet nevytvorili, tento e-mail môžete ignorovať.
					</p>
				</div>
			`,
			text: [
				"QUESTPIE Autopilot — overte svoj e-mail",
				"",
				`Dobrý deň ${input.name}, ďakujeme za registráciu.`,
				"Pre aktiváciu účtu potvrďte svoju e-mailovú adresu otvorením tohto odkazu:",
				"",
				input.verifyUrl,
				"",
				"Ak ste si účet nevytvorili, tento e-mail môžete ignorovať.",
			].join("\n"),
		};
	},
});
