/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedInvitationRouteImport } from './routes/_authenticated/invitation'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAppCompanySlugRouteImport } from './routes/_authenticated/app/$companySlug'
import { Route as AuthenticatedOnboardingAiRouteImport } from './routes/_authenticated/onboarding/ai'
import { Route as AuthenticatedOnboardingCompanyRouteImport } from './routes/_authenticated/onboarding/company'
import { Route as AuthenticatedOnboardingTeamRouteImport } from './routes/_authenticated/onboarding/team'
import { Route as AuthenticatedOnboardingWorkRouteImport } from './routes/_authenticated/onboarding/work'
import { Route as AuthenticatedAppCompanySlugActivityRouteImport } from './routes/_authenticated/app/$companySlug/activity'
import { Route as AuthenticatedAppCompanySlugHomeRouteImport } from './routes/_authenticated/app/$companySlug/home'
import { Route as AuthenticatedAppCompanySlugNeedsYouRouteImport } from './routes/_authenticated/app/$companySlug/needs-you'
import { Route as AuthenticatedAppCompanySlugTeamRouteImport } from './routes/_authenticated/app/$companySlug/team'
import { Route as AuthenticatedAppCompanySlugSettingsAiRouteImport } from './routes/_authenticated/app/$companySlug/settings.ai'
import { Route as AuthenticatedAppCompanySlugSpacesIndexRouteImport } from './routes/_authenticated/app/$companySlug/spaces.index'
import { Route as AuthenticatedAppCompanySlugSpacesSpaceSlugRouteImport } from './routes/_authenticated/app/$companySlug/spaces.$spaceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvitationRoute = AuthenticatedInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppCompanySlugRoute =
  AuthenticatedAppCompanySlugRouteImport.update({
    id: '/app/$companySlug',
    path: '/app/$companySlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingAiRoute =
  AuthenticatedOnboardingAiRouteImport.update({
    id: '/onboarding/ai',
    path: '/onboarding/ai',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingCompanyRoute =
  AuthenticatedOnboardingCompanyRouteImport.update({
    id: '/onboarding/company',
    path: '/onboarding/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingTeamRoute =
  AuthenticatedOnboardingTeamRouteImport.update({
    id: '/onboarding/team',
    path: '/onboarding/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingWorkRoute =
  AuthenticatedOnboardingWorkRouteImport.update({
    id: '/onboarding/work',
    path: '/onboarding/work',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCompanySlugActivityRoute =
  AuthenticatedAppCompanySlugActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugHomeRoute =
  AuthenticatedAppCompanySlugHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugNeedsYouRoute =
  AuthenticatedAppCompanySlugNeedsYouRouteImport.update({
    id: '/needs-you',
    path: '/needs-you',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugTeamRoute =
  AuthenticatedAppCompanySlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugSettingsAiRoute =
  AuthenticatedAppCompanySlugSettingsAiRouteImport.update({
    id: '/settings/ai',
    path: '/settings/ai',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugSpacesIndexRoute =
  AuthenticatedAppCompanySlugSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)
const AuthenticatedAppCompanySlugSpacesSpaceSlugRoute =
  AuthenticatedAppCompanySlugSpacesSpaceSlugRouteImport.update({
    id: '/spaces/$spaceSlug',
    path: '/spaces/$spaceSlug',
    getParentRoute: () => AuthenticatedAppCompanySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/$companySlug': typeof AuthenticatedAppCompanySlugRouteWithChildren
  '/onboarding/ai': typeof AuthenticatedOnboardingAiRoute
  '/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/onboarding/team': typeof AuthenticatedOnboardingTeamRoute
  '/onboarding/work': typeof AuthenticatedOnboardingWorkRoute
  '/app/$companySlug/activity': typeof AuthenticatedAppCompanySlugActivityRoute
  '/app/$companySlug/home': typeof AuthenticatedAppCompanySlugHomeRoute
  '/app/$companySlug/needs-you': typeof AuthenticatedAppCompanySlugNeedsYouRoute
  '/app/$companySlug/team': typeof AuthenticatedAppCompanySlugTeamRoute
  '/app/$companySlug/settings/ai': typeof AuthenticatedAppCompanySlugSettingsAiRoute
  '/app/$companySlug/spaces/$spaceSlug': typeof AuthenticatedAppCompanySlugSpacesSpaceSlugRoute
  '/app/$companySlug/spaces/': typeof AuthenticatedAppCompanySlugSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/$companySlug': typeof AuthenticatedAppCompanySlugRouteWithChildren
  '/onboarding/ai': typeof AuthenticatedOnboardingAiRoute
  '/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/onboarding/team': typeof AuthenticatedOnboardingTeamRoute
  '/onboarding/work': typeof AuthenticatedOnboardingWorkRoute
  '/app/$companySlug/activity': typeof AuthenticatedAppCompanySlugActivityRoute
  '/app/$companySlug/home': typeof AuthenticatedAppCompanySlugHomeRoute
  '/app/$companySlug/needs-you': typeof AuthenticatedAppCompanySlugNeedsYouRoute
  '/app/$companySlug/team': typeof AuthenticatedAppCompanySlugTeamRoute
  '/app/$companySlug/settings/ai': typeof AuthenticatedAppCompanySlugSettingsAiRoute
  '/app/$companySlug/spaces/$spaceSlug': typeof AuthenticatedAppCompanySlugSpacesSpaceSlugRoute
  '/app/$companySlug/spaces': typeof AuthenticatedAppCompanySlugSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/invitation': typeof AuthenticatedInvitationRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/app/$companySlug': typeof AuthenticatedAppCompanySlugRouteWithChildren
  '/_authenticated/onboarding/ai': typeof AuthenticatedOnboardingAiRoute
  '/_authenticated/onboarding/company': typeof AuthenticatedOnboardingCompanyRoute
  '/_authenticated/onboarding/team': typeof AuthenticatedOnboardingTeamRoute
  '/_authenticated/onboarding/work': typeof AuthenticatedOnboardingWorkRoute
  '/_authenticated/app/$companySlug/activity': typeof AuthenticatedAppCompanySlugActivityRoute
  '/_authenticated/app/$companySlug/home': typeof AuthenticatedAppCompanySlugHomeRoute
  '/_authenticated/app/$companySlug/needs-you': typeof AuthenticatedAppCompanySlugNeedsYouRoute
  '/_authenticated/app/$companySlug/team': typeof AuthenticatedAppCompanySlugTeamRoute
  '/_authenticated/app/$companySlug/settings/ai': typeof AuthenticatedAppCompanySlugSettingsAiRoute
  '/_authenticated/app/$companySlug/spaces/$spaceSlug': typeof AuthenticatedAppCompanySlugSpacesSpaceSlugRoute
  '/_authenticated/app/$companySlug/spaces/': typeof AuthenticatedAppCompanySlugSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/invitation'
    | '/api/$'
    | '/invite/$token'
    | '/app/$companySlug'
    | '/onboarding/ai'
    | '/onboarding/company'
    | '/onboarding/team'
    | '/onboarding/work'
    | '/app/$companySlug/activity'
    | '/app/$companySlug/home'
    | '/app/$companySlug/needs-you'
    | '/app/$companySlug/team'
    | '/app/$companySlug/settings/ai'
    | '/app/$companySlug/spaces/$spaceSlug'
    | '/app/$companySlug/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/invitation'
    | '/api/$'
    | '/invite/$token'
    | '/app/$companySlug'
    | '/onboarding/ai'
    | '/onboarding/company'
    | '/onboarding/team'
    | '/onboarding/work'
    | '/app/$companySlug/activity'
    | '/app/$companySlug/home'
    | '/app/$companySlug/needs-you'
    | '/app/$companySlug/team'
    | '/app/$companySlug/settings/ai'
    | '/app/$companySlug/spaces/$spaceSlug'
    | '/app/$companySlug/spaces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/invitation'
    | '/api/$'
    | '/invite/$token'
    | '/_authenticated/app/$companySlug'
    | '/_authenticated/onboarding/ai'
    | '/_authenticated/onboarding/company'
    | '/_authenticated/onboarding/team'
    | '/_authenticated/onboarding/work'
    | '/_authenticated/app/$companySlug/activity'
    | '/_authenticated/app/$companySlug/home'
    | '/_authenticated/app/$companySlug/needs-you'
    | '/_authenticated/app/$companySlug/team'
    | '/_authenticated/app/$companySlug/settings/ai'
    | '/_authenticated/app/$companySlug/spaces/$spaceSlug'
    | '/_authenticated/app/$companySlug/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation': {
      id: '/_authenticated/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof AuthenticatedInvitationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/$companySlug': {
      id: '/_authenticated/app/$companySlug'
      path: '/app/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/ai': {
      id: '/_authenticated/onboarding/ai'
      path: '/onboarding/ai'
      fullPath: '/onboarding/ai'
      preLoaderRoute: typeof AuthenticatedOnboardingAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/company': {
      id: '/_authenticated/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof AuthenticatedOnboardingCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/team': {
      id: '/_authenticated/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof AuthenticatedOnboardingTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/work': {
      id: '/_authenticated/onboarding/work'
      path: '/onboarding/work'
      fullPath: '/onboarding/work'
      preLoaderRoute: typeof AuthenticatedOnboardingWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$companySlug/activity': {
      id: '/_authenticated/app/$companySlug/activity'
      path: '/activity'
      fullPath: '/app/$companySlug/activity'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugActivityRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/home': {
      id: '/_authenticated/app/$companySlug/home'
      path: '/home'
      fullPath: '/app/$companySlug/home'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugHomeRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/needs-you': {
      id: '/_authenticated/app/$companySlug/needs-you'
      path: '/needs-you'
      fullPath: '/app/$companySlug/needs-you'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugNeedsYouRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/team': {
      id: '/_authenticated/app/$companySlug/team'
      path: '/team'
      fullPath: '/app/$companySlug/team'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugTeamRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/settings/ai': {
      id: '/_authenticated/app/$companySlug/settings/ai'
      path: '/settings/ai'
      fullPath: '/app/$companySlug/settings/ai'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugSettingsAiRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/spaces/': {
      id: '/_authenticated/app/$companySlug/spaces/'
      path: '/spaces'
      fullPath: '/app/$companySlug/spaces/'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
    '/_authenticated/app/$companySlug/spaces/$spaceSlug': {
      id: '/_authenticated/app/$companySlug/spaces/$spaceSlug'
      path: '/spaces/$spaceSlug'
      fullPath: '/app/$companySlug/spaces/$spaceSlug'
      preLoaderRoute: typeof AuthenticatedAppCompanySlugSpacesSpaceSlugRouteImport
      parentRoute: typeof AuthenticatedAppCompanySlugRoute
    }
  }
}

interface AuthenticatedAppCompanySlugRouteChildren {
  AuthenticatedAppCompanySlugActivityRoute: typeof AuthenticatedAppCompanySlugActivityRoute
  AuthenticatedAppCompanySlugHomeRoute: typeof AuthenticatedAppCompanySlugHomeRoute
  AuthenticatedAppCompanySlugNeedsYouRoute: typeof AuthenticatedAppCompanySlugNeedsYouRoute
  AuthenticatedAppCompanySlugTeamRoute: typeof AuthenticatedAppCompanySlugTeamRoute
  AuthenticatedAppCompanySlugSettingsAiRoute: typeof AuthenticatedAppCompanySlugSettingsAiRoute
  AuthenticatedAppCompanySlugSpacesSpaceSlugRoute: typeof AuthenticatedAppCompanySlugSpacesSpaceSlugRoute
  AuthenticatedAppCompanySlugSpacesIndexRoute: typeof AuthenticatedAppCompanySlugSpacesIndexRoute
}

const AuthenticatedAppCompanySlugRouteChildren: AuthenticatedAppCompanySlugRouteChildren =
  {
    AuthenticatedAppCompanySlugActivityRoute:
      AuthenticatedAppCompanySlugActivityRoute,
    AuthenticatedAppCompanySlugHomeRoute: AuthenticatedAppCompanySlugHomeRoute,
    AuthenticatedAppCompanySlugNeedsYouRoute:
      AuthenticatedAppCompanySlugNeedsYouRoute,
    AuthenticatedAppCompanySlugTeamRoute: AuthenticatedAppCompanySlugTeamRoute,
    AuthenticatedAppCompanySlugSettingsAiRoute:
      AuthenticatedAppCompanySlugSettingsAiRoute,
    AuthenticatedAppCompanySlugSpacesSpaceSlugRoute:
      AuthenticatedAppCompanySlugSpacesSpaceSlugRoute,
    AuthenticatedAppCompanySlugSpacesIndexRoute:
      AuthenticatedAppCompanySlugSpacesIndexRoute,
  }

const AuthenticatedAppCompanySlugRouteWithChildren =
  AuthenticatedAppCompanySlugRoute._addFileChildren(
    AuthenticatedAppCompanySlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedInvitationRoute: typeof AuthenticatedInvitationRoute
  AuthenticatedAppCompanySlugRoute: typeof AuthenticatedAppCompanySlugRouteWithChildren
  AuthenticatedOnboardingAiRoute: typeof AuthenticatedOnboardingAiRoute
  AuthenticatedOnboardingCompanyRoute: typeof AuthenticatedOnboardingCompanyRoute
  AuthenticatedOnboardingTeamRoute: typeof AuthenticatedOnboardingTeamRoute
  AuthenticatedOnboardingWorkRoute: typeof AuthenticatedOnboardingWorkRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInvitationRoute: AuthenticatedInvitationRoute,
  AuthenticatedAppCompanySlugRoute:
    AuthenticatedAppCompanySlugRouteWithChildren,
  AuthenticatedOnboardingAiRoute: AuthenticatedOnboardingAiRoute,
  AuthenticatedOnboardingCompanyRoute: AuthenticatedOnboardingCompanyRoute,
  AuthenticatedOnboardingTeamRoute: AuthenticatedOnboardingTeamRoute,
  AuthenticatedOnboardingWorkRoute: AuthenticatedOnboardingWorkRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiSplatRoute: ApiSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
