/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_activity_events from "../collections/activity-events";
import _coll_actor_invitations from "../collections/actor-invitations";
import _coll_actor_role_bindings from "../collections/actor-role-bindings";
import _coll_actors from "../collections/actors";
import _coll_audit_events from "../collections/audit-events";
import _coll_command_receipts from "../collections/command-receipts";
import _coll_companies from "../collections/companies";
import _coll_invitation_challenges from "../collections/invitation-challenges";
import _coll_projects from "../collections/projects";
import _coll_roles from "../collections/roles";
import _coll_space_memberships from "../collections/space-memberships";
import _coll_spaces from "../collections/spaces";

// ── Channels ───────────────────────────────────────────────
import _channel_harnessProbe from "../channels/harness-probe";

// ── Routes ─────────────────────────────────────────────────
import _route_actors_archive from "../routes/actors/archive";
import _route_actors_reactivate from "../routes/actors/reactivate";
import _route_actors_suspend from "../routes/actors/suspend";
import _route_companies_bootstrap from "../routes/companies/bootstrap";
import _route_invitations_accept from "../routes/invitations/accept";
import _route_invitations_challenge from "../routes/invitations/challenge";
import _route_invitations_exchange from "../routes/invitations/exchange";
import _route_invitations_issue from "../routes/invitations/issue";
import _route_invitations_resend from "../routes/invitations/resend";
import _route_invitations_revoke from "../routes/invitations/revoke";
import _route_projects_archive from "../routes/projects/archive";
import _route_projects_create from "../routes/projects/create";
import _route_projects_rename from "../routes/projects/rename";
import _route_projects_restore from "../routes/projects/restore";
import _route_roleBindings_replace from "../routes/role-bindings/replace";
import _route_spaceMemberships_add from "../routes/space-memberships/add";
import _route_spaceMemberships_change from "../routes/space-memberships/change";
import _route_spaceMemberships_remove from "../routes/space-memberships/remove";
import _route_spaces_archive from "../routes/spaces/archive";
import _route_spaces_create from "../routes/spaces/create";
import _route_spaces_restore from "../routes/spaces/restore";
import _route_spaces_update from "../routes/spaces/update";

// ── Services ───────────────────────────────────────────────
import { default as _svc_organizationDomain } from "../services/organization-domain";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260719T094552_phase0Organization from "../migrations/20260719T094552_phase-0-organization";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _mcpConfig from "../config/mcp";
import _openapi from "../config/openapi";

import type { AppCollections, AppChannels, AppGlobals, AppJobs, _ModuleCollections, _AppDefaultServices, _AppServicesSeam, _AppTopLevelServices, _AppCustomServiceNamespaces, AppWorkflows, _Registry_Collections, _Registry_Channels, _Registry_Globals, _Registry_Jobs, _Registry_Routes, _Registry_Services, _Registry_Emails, _Registry_FieldTypes, _Registry_Workflows, _Registry_McpTools, _AllModuleFields } from "./entities.gen";
import type { AnyCollectionOrBuilder, AnyGlobalOrBuilder, CollectionAPI, DrizzleClientFromQuestpieConfig, InferContextExtensionsFromAppConfig, InferSessionFromAuthConfig, MailerService, Questpie, QuestpieConfig, QueueClient, QueueJobType, ServiceInstancesInNamespace, TablesFromConfig, z } from "questpie/types";
import type { ChannelsService } from "questpie/channels";

import type { WorkflowClient } from "@questpie/workflows/server";
type _MPSubModules<M> = M extends { modules: infer S extends readonly any[] } ? S : readonly [];
type _MPConfigValue<M, K extends string> = M extends { config: infer C } ? (C extends Record<K, infer V> ? V : {}) : {};
type _MPConfigSub<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _MPConfigSub<_MPSubModules<H>, K> & _MPConfigValue<H, K> & _MPConfigSub<T, K> : {};
type _AppAppConfig = typeof _appConfig;
type _AppContextExtensions = Partial<InferContextExtensionsFromAppConfig<_AppAppConfig>>;
type _AppAuthConfig = _MPConfigSub<typeof _modules, "auth"> & typeof _authConfig;
type _AppSessionAuthConfig = _AppAuthConfig;
type _AppSession = NonNullable<InferSessionFromAuthConfig<_AppSessionAuthConfig>> | null;

export type AppRouteKeys = "spaceMemberships/change" | "spaceMemberships/remove" | "spaceMemberships/add" | "projects/restore" | "projects/archive" | "projects/rename" | "projects/create" | "spaces/restore" | "spaces/archive" | "spaces/create" | "spaces/update" | "roleBindings/replace" | "actors/archive" | "actors/suspend" | "actors/reactivate" | "companies/bootstrap" | "invitations/challenge" | "invitations/issue" | "invitations/resend" | "invitations/revoke" | "invitations/accept" | "invitations/exchange";

type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };
type _JobHandlerCollections = _ModuleCollections & {
	activity_events: typeof _coll_activity_events;
	actor_invitations: typeof _coll_actor_invitations;
	actor_role_bindings: typeof _coll_actor_role_bindings;
	actors: typeof _coll_actors;
	audit_events: typeof _coll_audit_events;
	command_receipts: typeof _coll_command_receipts;
	companies: typeof _coll_companies;
	invitation_challenges: typeof _coll_invitation_challenges;
	projects: typeof _coll_projects;
	roles: typeof _coll_roles;
	space_memberships: typeof _coll_space_memberships;
	spaces: typeof _coll_spaces;
};
type _JobHandlerCollectionsAPI = { [K in keyof _JobHandlerCollections]: CollectionAPI<_JobHandlerCollections[K], _JobHandlerCollections> };
type _ExecutionContextJob<T> = T extends { name: infer TName extends string; schema: z.ZodSchema<infer TPayload> } ? QueueJobType<TPayload, TName> : never;
type _ExecutionContextJobs = {};
type _ExecutionContextServiceDefinitions = {
	organizationDomain: typeof _svc_organizationDomain;
};
type _ExecutionContextDefaultServices = ServiceInstancesInNamespace<_ExecutionContextServiceDefinitions, "services">;
type _AppCollectionDefinitions = AppCollections & Record<string, AnyCollectionOrBuilder>;
type _AppGlobalDefinitions = AppGlobals & Record<string, AnyGlobalOrBuilder>;
type _AppQuestpieConfig = Omit<QuestpieConfig, "app" | "db" | "collections" | "channels" | "globals" | "auth" | "~contextExtensions"> & {
	app: (typeof _runtime)["app"];
	db: (typeof _runtime)["db"];
	collections: _AppCollectionDefinitions;
	channels: AppChannels;
	globals: _AppGlobalDefinitions;
	auth: _AppAuthConfig;
	storage: (typeof _runtime)["storage"];
	"~contextExtensions": _AppContextExtensions;
};
type _AppQuestpieBase = Questpie<_AppQuestpieConfig>;
type _AppDb = DrizzleClientFromQuestpieConfig<_AppQuestpieConfig>;
type _AppGlobalsAPI = _AppQuestpieBase["globals"];
type _AppStorage = _AppQuestpieBase["storage"];
type _AppTables = TablesFromConfig<_AppQuestpieConfig>;
export type _AppQuestpie = Omit<_AppQuestpieBase, "collections" | "globals"> & {
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
};

// ── AppContext augmentation — auto-types ALL handlers ──────
type _AppInfraRecord = {
	// Infrastructure
	app: _AppQuestpie;
	db: _AppDb;
	email: _AppQuestpie["email"];
	queue: QueueClient<AppJobs>;
	storage: _AppStorage;
	kv: _AppQuestpie["kv"];
	logger: _AppQuestpie["logger"];
	search: _AppQuestpie["search"];
	realtime: _AppQuestpie["realtime"];
	channels: ChannelsService<AppChannels>;

	// Entity APIs
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
	tables: _AppTables;

	// Request-scoped
	session: _AppSession;
	t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

	// User services
	services: _AppDefaultServices;
};
type _AppInfraContext = _AppInfraRecord & _AppCustomServiceNamespaces;
type _AppCoreContext = _AppContextExtensions & _AppInfraContext;
type _ServiceCreateInfra = Omit<_AppInfraRecord, "services"> & { services: Questpie.Services };

declare global {
	namespace Questpie {
		interface AppContext extends _AppCoreContext, _AppTopLevelServices {
			workflows: WorkflowClient<AppWorkflows>;
		}

		interface JobHandlerContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];
			channels: ChannelsService<AppChannels>;

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Workflows client — typed by AppWorkflows (name + schema preserved)
			workflows: WorkflowClient<AppWorkflows>;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface WorkflowContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];
			channels: ChannelsService<AppChannels>;

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Workflows client — typed by AppWorkflows (name + schema preserved)
			workflows: WorkflowClient<AppWorkflows>;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface Services extends _AppServicesSeam {}
		interface ServiceCreateContext extends _AppContextExtensions, _ServiceCreateInfra {}
		// Names-only marker — the `ServiceCreateContext` fallback conditional
		// probes THIS interface's keys instead of the real one (whose base
		// resolves through module service definitions and would cycle).
		interface ServiceCreateContextGenerated { generated: unknown }

		// Typed service surface for appConfig({ context }) resolvers.
		// Excludes _AppContextExtensions — the resolver produces them.
		interface ContextResolverContext {
			collections: _CollectionsAPI;
			globals: _AppGlobalsAPI;
			logger: _AppQuestpie["logger"];
			kv: _AppQuestpie["kv"];
			queue: QueueClient<AppJobs>;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;
			services: _AppDefaultServices;
		}

		// App-level hook / default-access ctx infra seams (CL-05).
		// Filled with the real infra MINUS _AppContextExtensions, so the
		// app-level hooks/access predicates get precise db/session/
		// collections/globals/queue WITHOUT re-entering the extensions cycle.
		interface AppHookContext extends _AppInfraContext {}
		interface AppDefaultAccessContext extends _AppInfraContext {}

		// appConfig({ context }) resolver session/db — off the cyclic edge.
		interface ContextResolverBase {
			session: _AppSession;
			db: _AppDb;
		}

		interface Registry {
			collections: _Registry_Collections;
			channels: _Registry_Channels;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;
			workflows: _Registry_Workflows;
			mcpTools: _Registry_McpTools;
		}
	}
}

/** Resolved auth session for this app (`{ user, session } | null`). */
export type AppAuthConfig = _AppAuthConfig;

export type AppSession = _AppSession;

/** Authenticated user shape from the app session. */
export type AppSessionUser = NonNullable<_AppSession>["user"];
