/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import "./names.gen";
// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_activity_events from "../collections/activity-events";
import _coll_actor_invitations from "../collections/actor-invitations";
import _coll_actor_role_bindings from "../collections/actor-role-bindings";
import _coll_actors from "../collections/actors";
import _coll_audit_events from "../collections/audit-events";
import _coll_channels from "../collections/channels";
import _coll_command_receipts from "../collections/command-receipts";
import _coll_companies from "../collections/companies";
import _coll_invitation_challenges from "../collections/invitation-challenges";
import _coll_projects from "../collections/projects";
import _coll_roles from "../collections/roles";
import _coll_space_memberships from "../collections/space-memberships";
import _coll_spaces from "../collections/spaces";

// ── Channels ───────────────────────────────────────────────
import _channel_harnessProbe from "../channels/harness-probe";

// ── Routes ─────────────────────────────────────────────────
import _route_actors_archive from "../routes/actors/archive";
import _route_actors_reactivate from "../routes/actors/reactivate";
import _route_actors_suspend from "../routes/actors/suspend";
import _route_companies_bootstrap from "../routes/companies/bootstrap";
import _route_invitations_accept from "../routes/invitations/accept";
import _route_invitations_challenge from "../routes/invitations/challenge";
import _route_invitations_exchange from "../routes/invitations/exchange";
import _route_invitations_issue from "../routes/invitations/issue";
import _route_invitations_resend from "../routes/invitations/resend";
import _route_invitations_revoke from "../routes/invitations/revoke";
import _route_projects_archive from "../routes/projects/archive";
import _route_projects_create from "../routes/projects/create";
import _route_projects_rename from "../routes/projects/rename";
import _route_projects_restore from "../routes/projects/restore";
import _route_roleBindings_replace from "../routes/role-bindings/replace";
import _route_spaceMemberships_add from "../routes/space-memberships/add";
import _route_spaceMemberships_change from "../routes/space-memberships/change";
import _route_spaceMemberships_remove from "../routes/space-memberships/remove";
import _route_spaces_archive from "../routes/spaces/archive";
import _route_spaces_create from "../routes/spaces/create";
import _route_spaces_restore from "../routes/spaces/restore";
import _route_spaces_update from "../routes/spaces/update";

// ── Services ───────────────────────────────────────────────
import { default as _svc_organizationDomain } from "../services/organization-domain";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260719T094552_phase0Organization from "../migrations/20260719T094552_phase-0-organization";
import _mig_20260720T225858_phase0Channels from "../migrations/20260720T225858_phase-0-channels";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _mcpConfig from "../config/mcp";
import _openapi from "../config/openapi";

import type { RouteParamsFromKey, RouteWithParams } from "questpie/types";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ExtractModulePropArr, ExtractModulePropArrOverride, Override, ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances } from "questpie/types";
type _RouteDefinitionWithoutHandler<T> = T extends { mode: "raw" } ? Omit<T, "handler"> & { handler: (args: unknown) => Response | Promise<Response> } : Omit<T, "handler"> & { handler: (args: unknown) => unknown | Promise<unknown> };
export type _ModuleCollections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _ModuleChannels = ExtractModulePropArr<typeof _modules, "channels">;
export type _ModuleGlobals = ExtractModulePropArr<typeof _modules, "globals">;
export type _ModuleJobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _ModuleRoutes = ExtractModulePropArr<typeof _modules, "routes">;
export type _ModuleServices = {};
export type _ModuleFieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _ModuleWorkflows = ExtractModulePropArr<typeof _modules, "workflows">;
export type _ModuleMcpTools = ExtractModulePropArr<typeof _modules, "mcpTools">;
// Registry category extraction from modules
export type _Registry_Collections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _Registry_Channels = ExtractModulePropArr<typeof _modules, "channels">;
export type _Registry_Globals = ExtractModulePropArr<typeof _modules, "globals">;
export type _Registry_Jobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _Registry_Routes = ExtractModulePropArr<typeof _modules, "routes">;
export type _Registry_Services = {};
export type _Registry_Emails = ExtractModulePropArr<typeof _modules, "emails">;
export type _Registry_FieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _Registry_Workflows = ExtractModulePropArr<typeof _modules, "workflows">;
export type _Registry_McpTools = ExtractModulePropArr<typeof _modules, "mcpTools">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie/types";

export type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = Override<_ModuleCollections, {
	activity_events: typeof _coll_activity_events;
	actor_invitations: typeof _coll_actor_invitations;
	actor_role_bindings: typeof _coll_actor_role_bindings;
	actors: typeof _coll_actors;
	audit_events: typeof _coll_audit_events;
	channels: typeof _coll_channels;
	command_receipts: typeof _coll_command_receipts;
	companies: typeof _coll_companies;
	invitation_challenges: typeof _coll_invitation_challenges;
	projects: typeof _coll_projects;
	roles: typeof _coll_roles;
	space_memberships: typeof _coll_space_memberships;
	spaces: typeof _coll_spaces;
}>;

/** All channels in the app (modules + user, user overrides) */
export type AppChannels = _ModuleChannels & {
	harnessProbe: typeof _channel_harnessProbe;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals;

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes & {
	"actors/archive": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_actors_archive>, RouteParamsFromKey<"actors/archive">>;
	"actors/reactivate": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_actors_reactivate>, RouteParamsFromKey<"actors/reactivate">>;
	"actors/suspend": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_actors_suspend>, RouteParamsFromKey<"actors/suspend">>;
	"companies/bootstrap": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_companies_bootstrap>, RouteParamsFromKey<"companies/bootstrap">>;
	"invitations/accept": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_accept>, RouteParamsFromKey<"invitations/accept">>;
	"invitations/challenge": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_challenge>, RouteParamsFromKey<"invitations/challenge">>;
	"invitations/exchange": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_exchange>, RouteParamsFromKey<"invitations/exchange">>;
	"invitations/issue": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_issue>, RouteParamsFromKey<"invitations/issue">>;
	"invitations/resend": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_resend>, RouteParamsFromKey<"invitations/resend">>;
	"invitations/revoke": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_invitations_revoke>, RouteParamsFromKey<"invitations/revoke">>;
	"projects/archive": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_projects_archive>, RouteParamsFromKey<"projects/archive">>;
	"projects/create": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_projects_create>, RouteParamsFromKey<"projects/create">>;
	"projects/rename": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_projects_rename>, RouteParamsFromKey<"projects/rename">>;
	"projects/restore": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_projects_restore>, RouteParamsFromKey<"projects/restore">>;
	"roleBindings/replace": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_roleBindings_replace>, RouteParamsFromKey<"roleBindings/replace">>;
	"spaceMemberships/add": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaceMemberships_add>, RouteParamsFromKey<"spaceMemberships/add">>;
	"spaceMemberships/change": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaceMemberships_change>, RouteParamsFromKey<"spaceMemberships/change">>;
	"spaceMemberships/remove": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaceMemberships_remove>, RouteParamsFromKey<"spaceMemberships/remove">>;
	"spaces/archive": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaces_archive>, RouteParamsFromKey<"spaces/archive">>;
	"spaces/create": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaces_create>, RouteParamsFromKey<"spaces/create">>;
	"spaces/restore": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaces_restore>, RouteParamsFromKey<"spaces/restore">>;
	"spaces/update": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_spaces_update>, RouteParamsFromKey<"spaces/update">>;
};

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices & {
	organizationDomain: typeof _svc_organizationDomain;
};

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
export type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
export type _AppServicesSeam = { [K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]> };
export type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
export type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;

/** All workflows in the app (modules + user, user overrides) */
export type AppWorkflows = _ModuleWorkflows;

/** All mcptools in the app (modules + user, user overrides) */
export type AppMcpTools = _ModuleMcpTools;
