/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, builtinFields, type EmptyCollectionState, type EmptyGlobalState, type BuiltinFields } from "questpie/builders";

// Merged field factories — builtins + module-contributed (e.g. richText, blocks) + user fields
const _rawFieldDefs = { ...builtinFields } as const;

const _allFieldDefs = _rawFieldDefs;

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface CollectionKeys { activity_events: unknown; actor_invitations: unknown; actor_role_bindings: unknown; actors: unknown; audit_events: unknown; channels: unknown; command_receipts: unknown; companies: unknown; invitation_challenges: unknown; projects: unknown; roles: unknown; space_memberships: unknown; spaces: unknown }
		interface ChannelKeys { harnessProbe: unknown }
		interface RouteKeys { "actors/archive": unknown; "actors/reactivate": unknown; "actors/suspend": unknown; "companies/bootstrap": unknown; "invitations/accept": unknown; "invitations/challenge": unknown; "invitations/exchange": unknown; "invitations/issue": unknown; "invitations/resend": unknown; "invitations/revoke": unknown; "projects/archive": unknown; "projects/create": unknown; "projects/rename": unknown; "projects/restore": unknown; "roleBindings/replace": unknown; "spaceMemberships/add": unknown; "spaceMemberships/change": unknown; "spaceMemberships/remove": unknown; "spaces/archive": unknown; "spaces/create": unknown; "spaces/restore": unknown; "spaces/update": unknown }
		interface ServiceKeys { organizationDomain: unknown }
	}
}

// ── Plugin Imports ─────────────────────────────────────────
import { type AppConfigInput, type AuthConfig } from "questpie/types";
import { type OpenApiModuleConfig } from "@questpie/openapi";
import { type WorkflowsConfigInput } from "@questpie/workflows/server";
import { type McpConfig } from "@questpie/mcp";

// Field types — populated by module codegen via Questpie.FieldTypesMap
type _AllFieldTypes = Questpie.FieldTypesMap;

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

/**
 * Create a typed collection builder with plugin extensions.
 *
 * @example
 * ```ts
 * import { collection } from "#questpie/factories";
 *
 * export default collection("posts")
 *   .fields(({ f }) => ({ title: f.text(255).required() }))
 * ```
 */
export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {
	return CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);
}

/**
 * Create a typed global builder with plugin extensions.
 */
export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {
	return GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);
}

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for appConfig config. */
export function appConfig<T extends AppConfigInput>(config: T): T { return config; }

/** Typed factory for authConfig config. */
export function authConfig<T extends AuthConfig>(config: T): T { return config; }

/** Typed factory for openapi config. */
export function openapi<T extends OpenApiModuleConfig>(config: T): T { return config; }

/** Typed factory for workflowsConfig config. */
export function workflowsConfig<T extends WorkflowsConfigInput>(config: T): T { return config; }

/** Typed factory for mcpConfig config. Accepts plain config or callback. */
export function mcpConfig<T extends McpConfig>(config: T): T;
export function mcpConfig<T extends (...args: never[]) => McpConfig>(cb: T): T;
export function mcpConfig<T>(v: T): T { return v; }
