/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory } from "questpie/app";
import "./names.gen";
import type { AccessContext, AppDefinition, CollectionSelect, GlobalSelect, HookContext, Where } from "questpie/types";
import type { AppCollections, AppChannels, AppGlobals, AppRoutes } from "./entities.gen";
import type { _AppQuestpie, AppAuthConfig, AppSession, AppSessionUser } from "./context.gen";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_activity_events from "../collections/activity-events";
import _coll_actor_invitations from "../collections/actor-invitations";
import _coll_actor_role_bindings from "../collections/actor-role-bindings";
import _coll_actors from "../collections/actors";
import _coll_audit_events from "../collections/audit-events";
import _coll_channels from "../collections/channels";
import _coll_command_receipts from "../collections/command-receipts";
import _coll_companies from "../collections/companies";
import _coll_invitation_challenges from "../collections/invitation-challenges";
import _coll_projects from "../collections/projects";
import _coll_roles from "../collections/roles";
import _coll_space_memberships from "../collections/space-memberships";
import _coll_spaces from "../collections/spaces";

// ── Channels ───────────────────────────────────────────────
import _channel_harnessProbe from "../channels/harness-probe";

// ── Routes ─────────────────────────────────────────────────
import _route_actors_archive from "../routes/actors/archive";
import _route_actors_reactivate from "../routes/actors/reactivate";
import _route_actors_suspend from "../routes/actors/suspend";
import _route_companies_bootstrap from "../routes/companies/bootstrap";
import _route_invitations_accept from "../routes/invitations/accept";
import _route_invitations_challenge from "../routes/invitations/challenge";
import _route_invitations_exchange from "../routes/invitations/exchange";
import _route_invitations_issue from "../routes/invitations/issue";
import _route_invitations_resend from "../routes/invitations/resend";
import _route_invitations_revoke from "../routes/invitations/revoke";
import _route_projects_archive from "../routes/projects/archive";
import _route_projects_create from "../routes/projects/create";
import _route_projects_rename from "../routes/projects/rename";
import _route_projects_restore from "../routes/projects/restore";
import _route_roleBindings_replace from "../routes/role-bindings/replace";
import _route_spaceMemberships_add from "../routes/space-memberships/add";
import _route_spaceMemberships_change from "../routes/space-memberships/change";
import _route_spaceMemberships_remove from "../routes/space-memberships/remove";
import _route_spaces_archive from "../routes/spaces/archive";
import _route_spaces_create from "../routes/spaces/create";
import _route_spaces_restore from "../routes/spaces/restore";
import _route_spaces_update from "../routes/spaces/update";

// ── Services ───────────────────────────────────────────────
import { default as _svc_organizationDomain } from "../services/organization-domain";

// ── Emails ─────────────────────────────────────────────────
import _email_verifyEmail from "../emails/verify-email";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260719T094552_phase0Organization from "../migrations/20260719T094552_phase-0-organization";
import _mig_20260720T225858_phase0Channels from "../migrations/20260720T225858_phase-0-channels";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _mcpConfig from "../config/mcp";
import _openapi from "../config/openapi";

export type * from "./entities.gen";
export type * from "./context.gen";

/**
 * Select/document type for a collection key — prefer over `Record<string, any>` for docs.
 */
export type CollectionDoc<K extends keyof AppCollections> = CollectionSelect<AppCollections[K]>;

/**
 * Select/document type for a global key.
 */
export type GlobalDoc<K extends keyof AppGlobals> = GlobalSelect<AppGlobals[K]>;

/**
 * Typed `where` filter for a collection key — prefer over `Record<string, unknown>`
 * when building a `where` clause dynamically before a `find`/`findOne` call.
 */
export type CollectionWhere<K extends keyof AppCollections> = Where<AppCollections[K], AppConfig>;

/**
 * Access-rule ctx for shared helpers. `K` narrows `data` to that collection's row.
 *
 * CYCLE RULE: import these only from files NOT imported by a collection
 * (routes, services, jobs, scripts). Helpers imported by collections take
 * the package-level `AccessContext` from "questpie" instead — see the
 * type-inference reference.
 *
 * @example
 * ```ts
 * export async function isOwner(ctx: AccessRuleContext<"posts">) {
 *   return ctx.data?.authorId === ctx.session?.user.id; // ctx.collections typed
 * }
 * ```
 */
export type AccessRuleContext<K extends keyof AppCollections | unknown = unknown> =
	AccessContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Hook ctx for shared helpers. `K` narrows `data` to that collection's row.
 * Same cycle rule as `AccessRuleContext`.
 */
export type HookRuleContext<K extends keyof AppCollections | unknown = unknown> =
	HookContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections;
	channels: AppChannels;
	globals: AppGlobals;
	routes: AppRoutes;
	storage: (typeof _runtime)["storage"];
	auth: AppAuthConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

var _appPromise: Promise<unknown> | undefined;

_appPromise = createApp(
	({
		modules: _modules,
		collections: {
			activity_events: _coll_activity_events,
			actor_invitations: _coll_actor_invitations,
			actor_role_bindings: _coll_actor_role_bindings,
			actors: _coll_actors,
			audit_events: _coll_audit_events,
			channels: _coll_channels,
			command_receipts: _coll_command_receipts,
			companies: _coll_companies,
			invitation_challenges: _coll_invitation_challenges,
			projects: _coll_projects,
			roles: _coll_roles,
			space_memberships: _coll_space_memberships,
			spaces: _coll_spaces,
		},
		channels: {
			harnessProbe: _channel_harnessProbe,
		},
		routes: {
			"actors/archive": _route_actors_archive,
			"actors/reactivate": _route_actors_reactivate,
			"actors/suspend": _route_actors_suspend,
			"companies/bootstrap": _route_companies_bootstrap,
			"invitations/accept": _route_invitations_accept,
			"invitations/challenge": _route_invitations_challenge,
			"invitations/exchange": _route_invitations_exchange,
			"invitations/issue": _route_invitations_issue,
			"invitations/resend": _route_invitations_resend,
			"invitations/revoke": _route_invitations_revoke,
			"projects/archive": _route_projects_archive,
			"projects/create": _route_projects_create,
			"projects/rename": _route_projects_rename,
			"projects/restore": _route_projects_restore,
			"roleBindings/replace": _route_roleBindings_replace,
			"spaceMemberships/add": _route_spaceMemberships_add,
			"spaceMemberships/change": _route_spaceMemberships_change,
			"spaceMemberships/remove": _route_spaceMemberships_remove,
			"spaces/archive": _route_spaces_archive,
			"spaces/create": _route_spaces_create,
			"spaces/restore": _route_spaces_restore,
			"spaces/update": _route_spaces_update,
		},
		services: {
			organizationDomain: _svc_organizationDomain,
		},
		emailTemplates: {
			verifyEmail: _email_verifyEmail,
		},
		migrations: [_mig_20260719T094552_phase0Organization, _mig_20260720T225858_phase0Channels],
		config: {
			app: _appConfig,
			auth: _authConfig,
			mcp: _mcpConfig,
			openapi: _openapi,
		},
	}) satisfies AppDefinition,
	_runtime,
);

export const app = (await _appPromise) as unknown as _AppQuestpie;

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export async function createContext(
	options?: Parameters<ReturnType<typeof createContextFactory>>[0],
) {
	while (!_appPromise) {
		await new Promise((resolve) => setTimeout(resolve, 0));
	}

	return createContextFactory((await _appPromise) as _AppQuestpie)(options);
}

// Factories: import { collection, global, ... } from '#questpie/factories';
