import { stableSelectors } from "../contracts";
import type { Phase0ScenarioCase } from "./types";

/**
 * F06-F10 scenario cases (AI-governance flows): permission decisions, cancel and
 * retry, agent-to-agent delegation, realtime-gap recovery, and provider or
 * capacity loss. Matrix METADATA only — no case here is executable proof, marks a
 * flow green, or extends the frozen registry vocabulary.
 */
export const phase0AiCases = [
	{
		id: "F06-P01-pause-approve-resume-journey",
		flow: "F06",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F06 flow row",
		obligations: ["US-PERMISSION-01", "US-NEEDS-01", "US-RUN-DETAIL-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"Marek sits inside the eligible-approver set snapshotted with the pending request.",
		fixtures: ["auth", "clock", "company", "evidence", "permissions", "queue", "rbac"],
		fixtureModes: [
			"permission:waiting",
			"permission:eligible-approver",
			"permission:delayed-acknowledgement",
			"needs:actionable",
		],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The permission request moves queued to delivered to outcome, and the same Run resumes only after the authorized decision lands.",
		absenceAssertions: [
			"No Run resumes before an authorized decision is recorded.",
			"No grant wider than the requested effect is created.",
		],
		selectors: [
			stableSelectors.screenNeedsYou,
			stableSelectors.screenRunDetail,
			stableSelectors.permissionDecisionApprove,
			stableSelectors.permissionRoutingState,
		],
	},
	{
		id: "F06-P02-deny-terminates-without-leak",
		flow: "F06",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F06 flow row",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState: "Marek remains an eligible approver and records an explicit deny decision.",
		fixtures: ["evidence", "permissions", "queue", "rbac"],
		fixtureModes: ["permission:denied"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"A deny decision terminates the paused Run with an attributable denied outcome on the Run detail.",
		absenceAssertions: [
			"No requested effect is committed after the deny decision.",
			"No existence or diagnostic leak accompanies the denial.",
		],
		selectors: [stableSelectors.permissionDecisionDeny, stableSelectors.screenRunDetail],
	},
	{
		id: "F06-P03-no-approver-configuration-route",
		flow: "F06",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F06 flow row",
		obligations: ["US-PERMISSION-01", "US-NEEDS-01"],
		actors: ["Autopilot / Agent"],
		permissionState:
			"No eligible approver exists for the requested effect; the routed recipient holds configuration-only authority.",
		fixtures: ["company", "evidence", "permissions"],
		fixtureModes: ["permission:no-approver", "needs:configuration-only"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Routing lands in an explicit no-approver state: the Run stays blocked while the recipient is offered configuration repair only.",
		absenceAssertions: [
			"No configuration-only recipient can record a decision.",
			"No Run resumes while the approver set stays empty.",
		],
		selectors: [stableSelectors.screenNeedsYou, stableSelectors.permissionRoutingState],
	},
	{
		id: "F06-N01-wrong-approver",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: wrong-approver + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent"],
		permissionState:
			"Decision attempted by a Human outside the snapshotted eligible-approver set; per prove-f06, Lucia receives no decision row unless eligible.",
		fixtures: ["auth", "evidence", "permissions", "rbac"],
		fixtureModes: ["permission:wrong-approver"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The wrong-approver attempt is denied and the paused Run stays paused with its request intact.",
		absenceAssertions: [
			"No decision by a non-eligible Human is accepted.",
			"No existence leak reveals the Run to the wrong approver.",
		],
		selectors: [stableSelectors.screenNeedsYou, stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N02-newly-ineligible-approver",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: newly-ineligible-approver + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"Marek was eligible at request snapshot time but lost approver eligibility before deciding.",
		fixtures: ["clock", "evidence", "permissions", "rbac"],
		fixtureModes: ["permission:newly-ineligible-approver"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The decision attempt after eligibility loss is rejected against current bindings and surfaced as a stale decision.",
		absenceAssertions: ["No decision from a newly ineligible approver commits an effect."],
		selectors: [stableSelectors.screenNeedsYou],
	},
	{
		id: "F06-N03-configuration-only-recipient-cannot-decide",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: configuration-only-recipient + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01", "US-NEEDS-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"The routed recipient holds configuration-only authority and sits outside the decision set.",
		fixtures: ["evidence", "permissions", "rbac"],
		fixtureModes: ["permission:configuration-only-recipient"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The configuration-only recipient sees repair affordances while decision controls stay withheld.",
		absenceAssertions: ["No configuration-only recipient can approve or deny the request."],
		selectors: [stableSelectors.screenNeedsYou, stableSelectors.permissionRoutingState],
	},
	{
		id: "F06-N04-expired-request",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: expired-request + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"Marek is an eligible approver, but the clock-controlled request deadline has passed.",
		fixtures: ["clock", "evidence", "permissions"],
		fixtureModes: ["permission:expired-request"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The expired request is closed as expired under the controlled clock and offers no live decision.",
		absenceAssertions: ["No decision on an expired request commits any effect."],
		selectors: [stableSelectors.screenNeedsYou],
	},
	{
		id: "F06-N05-expired-grant",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: expired-grant + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState: "An approval was recorded, but its grant expired before the Run consumed it.",
		fixtures: ["clock", "evidence", "permissions"],
		fixtureModes: ["permission:expired-grant"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Resume against the expired grant is fenced; the Run stays paused until a fresh decision exists.",
		absenceAssertions: ["No Run resumes on an expired grant."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N06-unknown-or-changed-effect",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: unknown-effect + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"Marek is eligible, but the requested effect no longer matches a known effect definition.",
		fixtures: ["evidence", "permissions", "queue"],
		fixtureModes: ["permission:unknown-effect"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The unknown or changed effect is rejected before any commit and reported as a safe failure.",
		absenceAssertions: ["No effect outside the snapshotted request payload is committed."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N07-forged-authority",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: forged-authority + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"A decision arrives carrying forged approver authority that no current binding backs.",
		fixtures: ["evidence", "permissions", "rbac"],
		fixtureModes: ["permission:forged-authority"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The forged decision is rejected against current bindings and leaves an attributable rejection trail.",
		absenceAssertions: ["No forged authority commits a decision or resumes the Run."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N08-revoked-access-removes-detail",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: revoked-access + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01", "US-RUN-DETAIL-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"The approver's access to the Run's anchor was revoked while the request was pending.",
		fixtures: ["evidence", "permissions", "rbac"],
		fixtureModes: ["permission:revoked-access", "run-detail:revoked"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Revocation removes the Run detail from the former approver without revealing whether the Run still exists.",
		absenceAssertions: ["No existence oracle survives access revocation."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N09-stale-principal-or-lease",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: stale-principal + stale-lease + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"The resuming worker presents a stale principal or an expired lease from before the decision.",
		fixtures: ["clock", "evidence", "permissions", "queue"],
		fixtureModes: ["permission:stale-principal", "permission:stale-lease"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Resume is fenced behind the current principal and a live lease; the stale resume attempt fails safely.",
		absenceAssertions: ["No stale principal or expired lease resumes the Run."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N10-duplicate-decision-idempotent",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: duplicate-decision + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState: "Marek's approval is delivered twice through the queue after a retry.",
		fixtures: ["evidence", "permissions", "queue"],
		fixtureModes: ["permission:duplicate-decision"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The duplicate decision delivery commits its effect at most once and the second delivery is absorbed.",
		absenceAssertions: ["No duplicate effect commit or second outcome transition occurs."],
		selectors: [stableSelectors.permissionDecisionApprove, stableSelectors.screenRunDetail],
	},
	{
		id: "F06-N11-approval-cannot-widen-other-runs",
		flow: "F06",
		kind: "negative",
		source:
			"fixture-profiles.F06 permissionModes: eligible-approver + prove-f06-exact-run-permission-decision negative oracle",
		obligations: ["US-PERMISSION-01"],
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		permissionState:
			"Marek approves one request scoped to a single Run, attempt, effect, and payload.",
		fixtures: ["company", "evidence", "permissions", "rbac"],
		fixtureModes: ["permission:eligible-approver"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The approval unblocks exactly the requesting Run attempt; sibling Runs with the same effect stay paused.",
		absenceAssertions: ["No other Run, attempt, effect, or payload is widened by the grant."],
		selectors: [stableSelectors.permissionDecisionApprove, stableSelectors.screenRunDetail],
	},
	{
		id: "F07-P01-durable-cancel-at-safe-boundary",
		flow: "F07",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-CANCEL-01"],
		actors: ["Lucia / requester", "Autopilot / Agent"],
		permissionState:
			"Lucia cancels her own requested Run; cancellation authority is scoped to the requester.",
		fixtures: ["clock", "company", "evidence", "queue"],
		fixtureModes: ["run-cancel:queued", "run-cancel:delivered", "run-cancel:safe-boundary"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The cancel command is durably queued, delivered, and honored at a safe boundary; acknowledgement stays distinct from the terminal outcome.",
		absenceAssertions: ["No cancel acknowledgement is presented as the terminal outcome."],
		selectors: [stableSelectors.screenRunDetail, stableSelectors.runCancelAction],
	},
	{
		id: "F07-P02-explicit-retry-linked-attempt",
		flow: "F07",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-RETRY-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState:
			"Marek holds Space Lead authority; retry authority is re-resolved from current bindings, never copied from the failed attempt.",
		fixtures: ["company", "evidence", "queue", "rbac"],
		fixtureModes: [
			"run-retry:explicit-command",
			"run-retry:linked-attempt",
			"run-retry:fresh-authority",
		],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"An explicit retry command creates a linked fresh attempt whose authority is resolved from current bindings.",
		absenceAssertions: [
			"No retry starts implicitly or without an explicit command.",
			"No retry reuses the failed attempt's captured authority.",
		],
		selectors: [stableSelectors.screenRunDetail, stableSelectors.runRetryAction],
	},
	{
		id: "F07-P03-committed-effects-remain-visible",
		flow: "F07",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-DETAIL-01"],
		actors: ["Lucia / requester"],
		permissionState:
			"Lucia retains read access to the Run she requested after it reached a terminal state.",
		fixtures: ["company", "evidence"],
		fixtureModes: ["run-detail:terminal-history"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Terminal history keeps committed effects and failure evidence visible on the Run detail.",
		absenceAssertions: ["No committed effect or failure evidence is erased from terminal history."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F07-N01-late-or-duplicate-cancel-idempotent",
		flow: "F07",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-CANCEL-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState:
			"Marek issues cancel commands that arrive late and in duplicate through the delivery double.",
		fixtures: ["clock", "duplicate-delivery", "evidence", "queue"],
		fixtureModes: ["run-cancel:late", "run-cancel:duplicate"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Late and duplicate cancel deliveries are absorbed idempotently against the already-terminal attempt.",
		absenceAssertions: [
			"No duplicate terminal transition results from a late or duplicate cancel.",
			"No terminal attempt reopens under replayed cancel delivery.",
		],
		selectors: [stableSelectors.screenRunDetail, stableSelectors.runCancelAction],
	},
	{
		id: "F07-N02-terminal-attempt-immutable",
		flow: "F07",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-DETAIL-01"],
		actors: ["Autopilot / Agent"],
		permissionState:
			"The Agent's attempt is already terminal when a stale command against it is replayed.",
		fixtures: ["company", "evidence", "queue"],
		fixtureModes: ["run-detail:stale-command"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The stale command against the terminal attempt is rejected and the attempt record stays immutable.",
		absenceAssertions: ["No terminal attempt reopens or records a second terminal transition."],
		selectors: [stableSelectors.screenRunDetail],
	},
	{
		id: "F07-N03-retry-cannot-reuse-revoked-authority",
		flow: "F07",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-RETRY-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState:
			"Marek's binding that authorized the original attempt was revoked before the retry command.",
		fixtures: ["clock", "evidence", "queue", "rbac"],
		fixtureModes: ["run-retry:fresh-authority"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Retry re-resolves authority from current bindings and fails safely when only the revoked grant remains.",
		absenceAssertions: [
			"No retry runs on revoked authority or a stale Skill, policy, or lease.",
			"No committed effect of the failed attempt is erased by the retry path.",
		],
		selectors: [stableSelectors.runRetryAction, stableSelectors.screenRunDetail],
	},
	{
		id: "F07-N04-client-abort-not-durable-cancel",
		flow: "F07",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F07 flow row",
		obligations: ["US-RUN-CANCEL-01"],
		actors: ["Lucia / requester"],
		permissionState: "Lucia closes the client stream without issuing a durable cancel command.",
		fixtures: ["company", "evidence", "queue"],
		fixtureModes: ["run-cancel:queued"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The client abort leaves the Run running; only the durable queued cancel path can end it.",
		absenceAssertions: ["No stream abort is presented as a durable cancellation."],
		selectors: [stableSelectors.screenRunDetail, stableSelectors.runCancelAction],
	},
	{
		id: "F08-P01-dual-mention-independent-roots",
		flow: "F08",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F08 flow row",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"Architect and Critic are activated Agents admitted independently to the anchor Space.",
		fixtures: ["activated-agents", "company", "evidence", "queue", "rbac"],
		fixtureModes: ["agent-peers:independent-roots"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"One dual mention produces two independent root Runs with distinct identities, policies, cards, and results.",
		absenceAssertions: ["No merged magic response blends the two Agents' authorship."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F08-P02-allowed-child-delegation",
		flow: "F08",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F08 flow row",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"Architect delegates to Critic at depth 2 with fresh child authority resolved at admission.",
		fixtures: ["activated-agents", "evidence", "queue", "rbac"],
		fixtureModes: ["agent-peers:allowed-child"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The allowed child delegation admits Critic at depth 2 under the lineage guard with freshly resolved authority.",
		absenceAssertions: [
			"No child inherits parent or requester authority.",
			"No hidden nested SDK call bypasses the delegation seam.",
		],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-P03-rejection-as-attributable-thread-notice",
		flow: "F08",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F08 flow row",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"Architect's delegation exceeds policy, so the rejection must surface as attributable thread content.",
		fixtures: ["activated-agents", "company", "evidence"],
		fixtureModes: ["agent-peers:depth-rejected"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The rejected delegation appears as an attributable notice in the anchor Thread beside the run card.",
		absenceAssertions: ["No rejection is silent or detached from the anchor Thread."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F08-N01-missing-membership-admission",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 admissionCases: missing-membership + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent"],
		permissionState: "Architect lacks membership in the target Space at admission time.",
		fixtures: ["activated-agents", "evidence", "rbac"],
		fixtureModes: ["agent-peers:missing-membership"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Admission rejects the missing-membership delegation before any child Run exists.",
		absenceAssertions: ["No child Run or membership widening results from the rejected admission."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N02-inactive-agent-admission",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 admissionCases: inactive-agent + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent"],
		permissionState: "Architect is deactivated at the moment the delegation names it.",
		fixtures: ["activated-agents", "evidence"],
		fixtureModes: ["agent-peers:inactive-agent"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "Admission rejects the inactive Agent before any child Run is created.",
		absenceAssertions: ["No Run is dispatched to an inactive Agent."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N03-incompatible-runtime-admission",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 admissionCases: incompatible-runtime + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Critic / Agent"],
		permissionState:
			"Critic's runtime is incompatible with the requested delegation at admission time.",
		fixtures: ["activated-agents", "evidence"],
		fixtureModes: ["agent-peers:incompatible-runtime"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Admission rejects the incompatible-runtime delegation with a safe, attributable failure.",
		absenceAssertions: ["No fallback runtime is substituted for the incompatible Agent."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N04-depth-above-three-rejected",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 lineageCases: depth-exceeded + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"The delegation chain reaches depth 4 against the lineage guard's maximumDepth of 3.",
		fixtures: ["activated-agents", "evidence", "queue"],
		fixtureModes: ["agent-peers:depth-rejected"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The depth-4 delegation is rejected by the lineage guard while the depth-3 chain stays intact.",
		absenceAssertions: ["No delegation deeper than the depth-3 lineage guard is admitted."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N05-repeated-fingerprint-rejected",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 lineageCases: repeated-fingerprint + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"The delegation repeats an already-seen lineage fingerprint between the same Agents.",
		fixtures: ["activated-agents", "evidence", "queue"],
		fixtureModes: ["agent-peers:fingerprint-rejected"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The repeated-fingerprint delegation is rejected before dispatch and reported on the run card.",
		absenceAssertions: ["No repeated lineage fingerprint spawns a second child Run."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N06-sibling-lifecycle-isolation",
		flow: "F08",
		kind: "negative",
		source:
			"fixture-profiles.F08 siblingIsolationCases: failed + cancelled + prove-f08-bounded-independent-agent-delegation negative oracle",
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"Architect and Critic own sibling root Runs whose lifecycles must stay isolated.",
		fixtures: ["activated-agents", "clock", "evidence", "queue"],
		fixtureModes: ["agent-peers:sibling-failure", "agent-peers:sibling-cancel"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"One sibling failing and the other being cancelled leaves each unaffected sibling running to its own outcome.",
		absenceAssertions: [
			"No sibling Run is mutated by the other sibling's failure or cancel.",
			"No cross-anchor widening follows a sibling lifecycle change.",
		],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F08-N07-duplicate-child-delivery-one-run",
		flow: "F08",
		kind: "negative",
		source:
			'prove-f08-bounded-independent-agent-delegation: negative oracle "duplicate child delivery"',
		obligations: ["US-AGENT-PEERS-01"],
		actors: ["Architect / Agent", "Critic / Agent"],
		permissionState:
			"The delegation's child work request is delivered twice through the duplicate-delivery double.",
		fixtures: ["activated-agents", "duplicate-delivery", "evidence", "queue"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Exactly one child request and one child Run exist per delegation despite duplicate delivery.",
		absenceAssertions: ["No duplicate child Run or duplicate child result is produced."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F09-P01-disconnect-stale-visible-reconnecting",
		flow: "F09",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01"],
		actors: ["Lucia / Space Member"],
		permissionState: "Lucia keeps her Space membership throughout the transport disconnect.",
		fixtures: ["auth", "company", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:disconnect"],
		layer: "realtime",
		serverRequirement: "real-http",
		positiveObservation:
			"During the disconnect the persisted Thread truth stays visible and an explicit reconnecting state is shown.",
		absenceAssertions: ["No blank-slate flash replaces persisted truth during the gap."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.realtimeState],
	},
	{
		id: "F09-P02-bounded-replay-resume",
		flow: "F09",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01"],
		actors: ["Lucia / Space Member"],
		permissionState:
			"Lucia's access is unchanged across the reconnect; replay resumes from her cursor.",
		fixtures: ["company", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:bounded-replay"],
		layer: "realtime",
		serverRequirement: "real-http",
		positiveObservation:
			"Reconnect resumes from the stored cursor with bounded replay reconciled by stable ids.",
		absenceAssertions: ["No unbounded replay or id-less reconciliation occurs."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.realtimeState],
	},
	{
		id: "F09-P03-gap-refetch-reconcile-nonce",
		flow: "F09",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01", "US-THREAD-01"],
		actors: ["Lucia / Space Member"],
		permissionState: "Lucia sends an optimistic Message while the replay window has a gap.",
		fixtures: ["clock", "company", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:replay-gap"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The gap triggers a refetch and the optimistic Message reconciles by nonce and sequence into exactly one entity.",
		absenceAssertions: ["No optimistic duplicate survives nonce and sequence reconciliation."],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F09-N01-no-duplicates-after-gap",
		flow: "F09",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01"],
		actors: ["Lucia / Space Member"],
		permissionState:
			"Lucia's client replays a gap while the delivery double re-delivers overlapping events.",
		fixtures: ["company", "duplicate-delivery", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:replay-gap"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"After gap recovery each Message, work request, Run, and result exists exactly once.",
		absenceAssertions: [
			"No duplicate Message, work request, Run, or result appears after replay.",
			"No unread counter regresses across the gap.",
		],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F09-N02-replay-rechecks-current-access",
		flow: "F09",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01", "US-SCOPE-01"],
		actors: ["Lucia / Space Member"],
		permissionState:
			"Lucia's access to the Thread's Space was revoked during the disconnect window.",
		fixtures: ["auth", "company", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:access-revoked", "scope:revoked-while-open"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Replay re-checks current access and withholds revoked content while clearing the stale snapshot.",
		absenceAssertions: ["No protected content leaks across the gap under revoked access."],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F09-N03-no-success-before-truth-agrees",
		flow: "F09",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F09 flow row",
		obligations: ["US-QUERY-REALTIME-01"],
		actors: ["Lucia / Space Member"],
		permissionState:
			"Lucia acts during a disconnect; transport state alone cannot confirm her writes.",
		fixtures: ["company", "evidence", "realtime-gap"],
		fixtureModes: ["realtime:disconnect"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"No success is announced until persisted truth agrees after reconciliation; the reconnecting state stays explicit.",
		absenceAssertions: [
			"No success toast precedes reconciliation with persisted truth.",
			"No business write is derived from transport state.",
		],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.realtimeState],
	},
	{
		id: "F10-P01-known-invalid-rejects-before-run",
		flow: "F10",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01"],
		actors: ["Tomáš / Admin", "Lucia / requester"],
		permissionState:
			"Tomáš administers the provider binding; Lucia's request meets a known-invalid admission check.",
		fixtures: ["clock", "company", "evidence", "provider", "queue"],
		fixtureModes: ["capacity:known-invalid-admission"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Admission rejects the known-invalid configuration before any Run exists and posts a stable attributable notice in the anchor Thread.",
		absenceAssertions: ["No Run is created for a known-invalid provider configuration."],
		selectors: [stableSelectors.screenAiSetup, stableSelectors.messageRunCard],
	},
	{
		id: "F10-P02-transient-loss-queued-until-deadline",
		flow: "F10",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01"],
		actors: ["Lucia / requester"],
		permissionState:
			"Lucia's request holds a captured deadline while provider capacity is transiently lost.",
		fixtures: ["clock", "evidence", "provider", "queue"],
		fixtureModes: ["capacity:transient-loss", "capacity:captured-deadline"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The transient loss keeps the request queued with its clock-controlled captured deadline shown.",
		absenceAssertions: ["No queue wait continues silently past the captured deadline."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F10-P03-stable-retryable-failure-with-retry-path",
		flow: "F10",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01", "US-RUN-RETRY-01"],
		actors: ["Lucia / requester"],
		permissionState:
			"Lucia sees the stable failure; retry authority will be re-resolved from current bindings.",
		fixtures: ["clock", "company", "evidence", "provider", "rbac"],
		fixtureModes: ["capacity:retryable-failure", "run-retry:retryable-failure"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The retryable failure renders as a stable failure state with an explicit retry path toward a linked attempt.",
		absenceAssertions: ["No failure state flickers away or retries implicitly."],
		selectors: [stableSelectors.messageRunCard, stableSelectors.screenAiSetup],
	},
	{
		id: "F10-N01-no-fallback-model-or-runtime",
		flow: "F10",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Tomáš's configured model is invalid; no alternative binding is eligible.",
		fixtures: ["evidence", "provider"],
		fixtureModes: ["capacity:known-invalid-admission"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The invalid configuration surfaces on AI setup without any fallback model or runtime being selected.",
		absenceAssertions: ["No fallback model or runtime substitutes for the configured one."],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F10-N02-no-fake-run-or-success",
		flow: "F10",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01"],
		actors: ["Lucia / requester"],
		permissionState:
			"Lucia's request is admission-rejected before dispatch under known-invalid capacity.",
		fixtures: ["evidence", "provider", "queue"],
		fixtureModes: ["capacity:known-invalid-admission"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The rejected request yields an honest failure notice; no run card ever claims progress.",
		absenceAssertions: ["No fake Run or fake success is presented for the rejected request."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F10-N03-no-silent-wait-past-deadline",
		flow: "F10",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01"],
		actors: ["Lucia / requester"],
		permissionState:
			"Lucia's queued request carries an immutable captured deadline under the controlled clock.",
		fixtures: ["clock", "evidence", "provider", "queue"],
		fixtureModes: ["capacity:captured-deadline"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"When the captured deadline passes, the wait ends in an explicit outcome instead of continuing silently.",
		absenceAssertions: ["No deadline is silently extended and no queue grows unbounded."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F10-N04-no-secret-or-diagnostic-leak",
		flow: "F10",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F10 flow row",
		obligations: ["US-CAPACITY-LOSS-01", "US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Tomáš views the failed verification; provider diagnostics stay privileged.",
		fixtures: ["company", "evidence", "provider"],
		fixtureModes: ["ai-setup:invalid-credential"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The invalid-credential failure shows a safe summary on AI setup with secrets and raw diagnostics withheld.",
		absenceAssertions: ["No credential material or raw provider diagnostic leaks into the UI."],
		selectors: [stableSelectors.screenAiSetup],
	},
] as const satisfies readonly Phase0ScenarioCase[];
