import { stableSelectors } from "../contracts";
import type { Phase0ScenarioCase } from "./types";

/**
 * F01-F05 half of the Phase 0 case matrix (52 cases). Pure planning METADATA:
 * no entry here is executable proof, marks a flow green, or extends the frozen
 * contract/registry/fixture-profile vocabulary. The F06-F10 half lives in
 * ./ai-cases.ts; the barrel concatenates both into phase0CaseMatrix.
 */
export const phase0Cases = [
	{
		id: "F01-P01-founder-bootstrap-journey",
		flow: "F01",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-AUTH-01", "US-SETUP-01", "US-SPACES-01"],
		actors: ["Marek / Owner"],
		permissionState: "Anonymous visitor becomes the first Human Owner of a fresh Company.",
		fixtures: ["auth", "clock", "company", "evidence", "rbac"],
		fixtureModes: ["auth:anonymous-redirect", "setup:new-company", "spaces:whole-company-only"],
		layer: "browser",
		serverRequirement: "real-http",
		positiveObservation:
			"Sign-in, company, team, and work setup persist one Company with the protected #general Channel and a pending Autopilot marked Needs setup.",
		absenceAssertions: [
			"No provider secret is required to finish bootstrap.",
			"No fake Agent activity appears anywhere in the journey.",
			"No success state renders before server persistence confirms.",
		],
		selectors: [
			stableSelectors.screenSignIn,
			stableSelectors.screenCompanySetup,
			stableSelectors.screenTeamSetup,
			stableSelectors.screenWorkSetup,
			stableSelectors.screenSpaceDirectory,
			stableSelectors.screenSpaceOverview,
			stableSelectors.screenChannelThread,
			stableSelectors.chatComposer,
		],
	},
	{
		id: "F01-P02-lucia-invitation-acceptance",
		flow: "F01",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-INVITE-01"],
		actors: ["Marek / Owner", "Lucia / invited Human"],
		permissionState:
			"Lucia signs in as the invited account; roles and bindings were fixed at invite time.",
		fixtures: ["auth", "company", "invitations", "evidence"],
		fixtureModes: ["invitation:eligible"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"A single-use invitation token admits Lucia exactly once with the roles and bindings recorded at invite time.",
		absenceAssertions: [
			"No raw invitation token is exposed to any client surface.",
			"No binding is widened beyond what the invite recorded.",
		],
		selectors: [stableSelectors.screenInvitationAcceptance],
	},
	{
		id: "F01-P03-resumable-setup-continuation",
		flow: "F01",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-SETUP-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner returns mid-setup to a partially persisted Company.",
		fixtures: ["company", "clock", "evidence"],
		fixtureModes: ["setup:resumable-partial"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Server truth resumes the wizard at the correct step and the Slovak draft copy is preserved verbatim.",
		absenceAssertions: [
			"No completed step is replayed or re-persisted on resume.",
			"No draft text is lost when the session continues.",
		],
		selectors: [
			stableSelectors.screenCompanySetup,
			stableSelectors.screenTeamSetup,
			stableSelectors.screenWorkSetup,
		],
	},
	{
		id: "F01-P04-home-activity-persisted-truth",
		flow: "F01",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-HOME-01", "US-ACTIVITY-01"],
		actors: ["Marek / Owner", "Lucia / invited Human"],
		permissionState: "Owner and invited member each read Company home under their own membership.",
		fixtures: ["company", "evidence", "screen-states"],
		fixtureModes: ["home:populated", "activity:populated"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Home and activity render only persisted business events attributable to real Actors.",
		absenceAssertions: [
			"No fixture-only activity row reaches the rendered feed.",
			"No business event is duplicated across home and activity.",
			"No transport event is presented as a business event.",
		],
		selectors: [stableSelectors.screenCompanyHome, stableSelectors.screenCompanyActivity],
	},
	{
		id: "F01-P05-copy-and-adaptive-measurements",
		flow: "F01",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-COPY-01", "US-ADAPTIVE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner views populated surfaces; no mutation is attempted.",
		fixtures: ["company", "screen-states", "evidence"],
		fixtureModes: [
			"copy:long-company",
			"copy:long-work",
			"copy:long-actor",
			"copy:long-markdown",
			"adaptive:viewport-390",
			"adaptive:viewport-767",
			"adaptive:viewport-768",
			"adaptive:viewport-1023",
			"adaptive:viewport-1024",
			"adaptive:wide",
			"adaptive:keyboard",
			"adaptive:coarse-pointer",
			"adaptive:reduced-motion",
			"adaptive:safe-area",
		],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Long Slovak copy and every adaptive viewport, input, and motion mode stay measurable without loss; this is the owner proof other flows delegate to per the C-cell grid.",
		absenceAssertions: [
			"No copy overflow clips or truncates meaning on any measured surface.",
			"No adaptive mode causes horizontal page scroll or unreachable controls.",
		],
		selectors: [
			stableSelectors.screenCompanyHome,
			stableSelectors.screenChannelThread,
			stableSelectors.chatComposer,
		],
	},
	{
		id: "F01-N01-duplicate-bootstrap-idempotent",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-SETUP-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner replays a bootstrap submit against an already persisted Company.",
		fixtures: ["auth", "company", "evidence"],
		fixtureModes: ["setup:version-conflict"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The duplicate submit resolves against the existing Company and surfaces the persisted truth.",
		absenceAssertions: [
			"No second Company graph is created by the replayed submit.",
			"No duplicate bootstrap receipts are recorded.",
		],
		selectors: [stableSelectors.screenCompanySetup],
	},
	{
		id: "F01-N02-terminal-invitation-tokens",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-INVITE-01"],
		actors: ["Lucia / invited Human"],
		permissionState: "Lucia presents an expired, revoked, already-used, or superseded token.",
		fixtures: ["invitations", "clock", "company", "evidence"],
		fixtureModes: [
			"invitation:expired",
			"invitation:revoked",
			"invitation:already-used",
			"invitation:superseded-by-resend",
		],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"Each terminal token lands in a safe terminal state that explains the outcome without acting.",
		absenceAssertions: [
			"No raw token value is echoed back on any terminal path.",
			"No second acceptance receipt is written for a terminal token.",
		],
		selectors: [stableSelectors.screenInvitationAcceptance],
	},
	{
		id: "F01-N03-wrong-account-acceptor",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-INVITE-01"],
		actors: ["Lucia / invited Human"],
		permissionState: "Signed in under a non-invited account with no company membership.",
		fixtures: ["auth", "invitations", "company", "evidence"],
		fixtureModes: ["invitation:wrong-account"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The acceptance screen refuses the wrong account and points to signing in with the invited identity.",
		absenceAssertions: [
			"No identity merge is performed between the accounts.",
			"No duplicate Actor is created for the invited Human.",
		],
		selectors: [stableSelectors.screenInvitationAcceptance],
	},
	{
		id: "F01-N04-accept-resend-race-single-winner",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-INVITE-01"],
		actors: ["Marek / Owner", "Lucia / invited Human"],
		permissionState: "Owner resends while Lucia concurrently accepts the earlier token.",
		fixtures: ["invitations", "clock", "company", "evidence"],
		fixtureModes: ["invitation:accept-resend-race"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"Exactly one acceptance wins the race and membership reflects the invite-time bindings.",
		absenceAssertions: [
			"No binding is widened by the resend race.",
			"No two acceptances both succeed for one invited Human.",
		],
		selectors: [stableSelectors.screenInvitationAcceptance],
	},
	{
		id: "F01-N05-mention-gate-without-active-agent",
		flow: "F01",
		kind: "negative",
		source:
			"week-1-end-to-end-scenarios: F01 flow row (Mention explains the gate and creates no Run)",
		obligations: [],
		actors: ["Marek / Owner"],
		permissionState: "Owner mentions the pending Autopilot in a human-only Company.",
		fixtures: ["company", "screen-states", "evidence"],
		fixtureModes: ["home:empty-human-only"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The composer explains the activation gate in place of dispatching any work.",
		absenceAssertions: [
			"No Run is created from the gated Mention.",
			"No fake run card renders in the Thread.",
		],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.chatComposer],
	},
	{
		id: "F01-N06-company-role-not-widened-into-space",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F01 flow row",
		obligations: ["US-SCOPE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner holds a Company grant but no membership in the protected Space.",
		fixtures: ["rbac", "company", "auth", "evidence"],
		fixtureModes: ["scope:denied"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"The Space overview denies the Company-level grant with the uniform denied treatment.",
		absenceAssertions: [
			"No Company grant reads Space-scoped content.",
			"No existence detail leaks through the denial.",
		],
		selectors: [stableSelectors.screenSpaceOverview],
	},
	{
		id: "F01-N07-last-human-owner-survives-race",
		flow: "F01",
		kind: "negative",
		source:
			"week-1-end-to-end-scenarios: F01 flow row (last Human Owner survives races) + prove-f01 (at least one active Human Owner)",
		obligations: [],
		actors: ["Marek / Owner", "Lucia / invited Human"],
		permissionState: "Two concurrent removals target the final Human Owner seats.",
		fixtures: ["company", "rbac", "clock", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"At least one active Human Owner survives every interleaving of the removal race.",
		absenceAssertions: [
			"No Company is left with zero Human Owners.",
			"No partial removal commits when the guard rejects.",
		],
		selectors: [stableSelectors.screenTeamSetup],
	},
	{
		id: "F01-N08-credential-pending-single-submit",
		flow: "F01",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: US-AUTH-01 row (credential pending; no duplicate submit)",
		obligations: ["US-AUTH-01"],
		actors: ["Marek / Owner"],
		permissionState: "Anonymous sign-in submit is pending against a slow credential check.",
		fixtures: ["auth", "clock", "evidence"],
		fixtureModes: ["auth:credential-pending"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The pending submit is disabled and labelled while the credential check is in flight.",
		absenceAssertions: [
			"No duplicate submit fires while the first is pending.",
			"No raw auth error detail is rendered to the visitor.",
			"No protected content flashes before the session resolves.",
		],
		selectors: [stableSelectors.screenSignIn],
	},
	{
		id: "F02-P01-credential-verify-activate-journey",
		flow: "F02",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin", "Autopilot / Agent"],
		permissionState: "Admin submits a write-only provider credential and activates the Agent.",
		fixtures: ["auth", "provider", "clock", "company", "evidence", "rbac"],
		fixtureModes: ["ai-setup:verifying", "ai-setup:ready"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Verification shows a bounded observable delay and the ready state derives from the complete persisted binding.",
		absenceAssertions: [
			"No credential value is readable after submit.",
			"No activation succeeds before the binding is complete.",
		],
		selectors: [
			stableSelectors.screenAiSetup,
			stableSelectors.providerVerifyAction,
			stableSelectors.agentActivateAction,
		],
	},
	{
		id: "F02-P02-skip-preserves-human-work",
		flow: "F02",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin skips AI setup in a human-only Company.",
		fixtures: ["company", "provider", "evidence"],
		fixtureModes: ["ai-setup:unconfigured"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Skipping AI setup leaves every human workflow intact and the setup surface resumable.",
		absenceAssertions: [
			"No Agent is activated by skipping.",
			"No human capability is lost when setup is skipped.",
		],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F02-N01-invalid-credential",
		flow: "F02",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin verifies a credential the provider rejects as invalid.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:invalid-credential"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The invalid credential fails verification with a stable, attributable explanation.",
		absenceAssertions: [
			"No secret is echoed or read back after the failure.",
			"No activation path unlocks from a failed verification.",
		],
		selectors: [stableSelectors.screenAiSetup, stableSelectors.providerVerifyAction],
	},
	{
		id: "F02-N02-stale-verification",
		flow: "F02",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin attempts activation on a verification that has gone stale.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:stale-verification"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "Stale verification blocks activation until a fresh verify completes.",
		absenceAssertions: ["No stale verification is accepted as current readiness."],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F02-N03-model-less-or-retired-offering",
		flow: "F02",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin verifies a provider whose offering lists no usable model.",
		fixtures: ["provider", "evidence"],
		fixtureModes: ["ai-setup:model-less"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The model-less or retired offering is reported plainly and activation stays gated.",
		absenceAssertions: ["No Agent activates against a model-less offering."],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F02-N04-provider-unavailable",
		flow: "F02",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin verifies while the provider endpoint is unavailable.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:provider-unavailable"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "Provider unavailability is surfaced as a bounded, retryable state.",
		absenceAssertions: ["No silent fallback provider is substituted."],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F02-N05-worker-capacity-unavailable",
		flow: "F02",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F02 flow row",
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin activates while worker capacity is unavailable.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:worker-unavailable"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Missing worker capacity is reported as the accepted capacity-less state with a bounded wait.",
		absenceAssertions: [
			"No infinite spinner hides the capacity gap.",
			"No activation is faked while capacity is missing.",
		],
		selectors: [stableSelectors.screenAiSetup],
	},
	{
		id: "F02-N06-duplicate-activation-submit",
		flow: "F02",
		kind: "negative",
		source: 'prove-f02-provider-gated-autopilot-activation: acceptance case "duplicate-submit"',
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin double-submits activation around the verify boundary.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:verifying", "ai-setup:ready"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Exactly one activation commits and the ready state derives from the single persisted binding.",
		absenceAssertions: [
			"No duplicate activation is recorded.",
			"No raw ready toggle bypasses the derivation.",
		],
		selectors: [stableSelectors.agentActivateAction],
	},
	{
		id: "F02-N07-rotated-credential-goes-stale",
		flow: "F02",
		kind: "negative",
		source:
			'prove-f02-provider-gated-autopilot-activation: acceptance case "rotated" (spec NA row: rotation readiness)',
		obligations: ["US-AI-SETUP-01"],
		actors: ["Tomáš / Admin"],
		permissionState: "Admin rotates the provider credential after a successful verification.",
		fixtures: ["provider", "clock", "evidence"],
		fixtureModes: ["ai-setup:stale-verification", "ai-setup:verifying"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Rotation invalidates the prior verification and re-verify proceeds with a write-only credential.",
		absenceAssertions: [
			"No secret readback is possible after rotation.",
			"No ready state is silently retained across rotation.",
		],
		selectors: [stableSelectors.screenAiSetup, stableSelectors.providerVerifyAction],
	},
	{
		id: "F03-P01-space-channel-scope-journey",
		flow: "F03",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-SPACES-01", "US-SPACE-01", "US-CHANNELS-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner browses Celá firma and Marketing under full membership.",
		fixtures: ["spaces-channels", "company", "auth", "evidence", "rbac"],
		fixtureModes: ["spaces:whole-company-only", "space:empty-sections"],
		layer: "browser",
		serverRequirement: "real-http",
		positiveObservation:
			"The scope header preserves Celá firma → #general, Marketing → #general, and Marketing → #kampan as distinct anchors.",
		absenceAssertions: ["No scope header mixes Channels across Space anchors."],
		selectors: [
			stableSelectors.screenSpaceDirectory,
			stableSelectors.screenSpaceOverview,
			stableSelectors.screenChannelDirectory,
			stableSelectors.screenChannelThread,
		],
	},
	{
		id: "F03-P02-project-context-narrowing",
		flow: "F03",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-PROJECT-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner opens Project context inside a Space they belong to.",
		fixtures: ["company", "auth", "evidence", "rbac"],
		fixtureModes: ["project:loading", "project:optional-absent"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Project context narrows correctly and an absent optional Project returns safely to the Space overview.",
		absenceAssertions: ["No error surface replaces the safe return path for an absent Project."],
		selectors: [stableSelectors.screenProjectContext],
	},
	{
		id: "F03-P03-goal-criteria-activation",
		flow: "F03",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-GOAL-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner creates and activates a Goal with assessable Criteria.",
		fixtures: ["company", "evidence", "rbac"],
		fixtureModes: ["goal:empty-list"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation: "Goal progress derives from assessed Criteria records.",
		absenceAssertions: ["No progress value is derived from Task counts."],
		selectors: [
			stableSelectors.screenGoalList,
			stableSelectors.screenGoalDetail,
			stableSelectors.goalCriterionRow,
		],
	},
	{
		id: "F03-P04-task-creation-independent-assignees",
		flow: "F03",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-TASK-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner creates Tasks and assigns Humans and the Agent independently.",
		fixtures: ["company", "evidence", "rbac"],
		fixtureModes: ["task:empty-list"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Humans and the Agent are assigned independently without coupling their assignment records.",
		absenceAssertions: ["No Human assignment is implied or removed by an Agent assignment."],
		selectors: [
			stableSelectors.screenTaskList,
			stableSelectors.screenTaskDetail,
			stableSelectors.taskAssigneeTrigger,
		],
	},
	{
		id: "F03-P05-two-general-channels-distinct-anchors",
		flow: "F03",
		kind: "positive",
		source: "fixture-profiles.F03 channels + week-1-end-to-end-scenarios: Default Channel identity",
		obligations: ["US-CHANNELS-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner reads both system default Channels across two Spaces.",
		fixtures: ["spaces-channels", "company", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "Two system_default/general records persist with distinct Space anchors.",
		absenceAssertions: ["No cross-Space alias merges the two #general Channels."],
		selectors: [stableSelectors.screenChannelDirectory],
	},
	{
		id: "F03-N01-duplicate-slug-same-space",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-CHANNELS-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner creates a Channel slug that already exists in the same Space.",
		fixtures: ["spaces-channels", "company", "evidence"],
		fixtureModes: ["channels:slug-conflict"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"The conflict is local to the one Space and the creation draft is preserved.",
		absenceAssertions: [
			"No conflict is raised against slugs in other Spaces.",
			"No draft input is lost on the conflict.",
		],
		selectors: [stableSelectors.screenChannelDirectory],
	},
	{
		id: "F03-N02-cross-space-message-rejected",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-SCOPE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner posts toward a Channel anchored in a Space outside the write scope.",
		fixtures: ["company", "rbac", "evidence"],
		fixtureModes: ["scope:denied"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "The cross-Space Message is rejected with the uniform scope treatment.",
		absenceAssertions: ["No partial write survives the rejection."],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F03-N03-cross-space-relation-or-move-rejected",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-TASK-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner relates or moves a Task across Space boundaries.",
		fixtures: ["company", "evidence"],
		fixtureModes: ["task:mutation-error"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "The cross-Space relation or move is rejected as a typed mutation error.",
		absenceAssertions: ["No partial relation or half-moved Task persists."],
		selectors: [stableSelectors.screenTaskDetail],
	},
	{
		id: "F03-N04-stale-version-conflict-preserves-draft",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-GOAL-01", "US-TASK-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner edits Goal and Task records from a stale snapshot.",
		fixtures: ["company", "clock", "evidence"],
		fixtureModes: ["goal:version-conflict", "task:version-conflict"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Current server truth is identified and the local draft is kept for reconciliation.",
		absenceAssertions: [
			"No stale write silently overwrites newer server truth.",
			"No draft content is discarded by the conflict.",
		],
		selectors: [stableSelectors.screenGoalDetail, stableSelectors.screenTaskDetail],
	},
	{
		id: "F03-N05-invalid-transition-or-cycle",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-TASK-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner submits an invalid Task transition or dependency cycle.",
		fixtures: ["company", "evidence"],
		fixtureModes: ["task:mutation-error"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "The invalid transition or cycle is rejected as a typed mutation error.",
		absenceAssertions: ["No invalid state or cyclic dependency is persisted."],
		selectors: [stableSelectors.screenTaskDetail],
	},
	{
		id: "F03-N06-denied-vs-not-found-equivalence",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-SCOPE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner probes a denied Space and a missing Space id.",
		fixtures: ["rbac", "company", "auth", "evidence"],
		fixtureModes: ["scope:not-found", "scope:denied"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Denied and not-found render the same treatment; this is the owner proof of the universal scope row other flows delegate to.",
		absenceAssertions: ["No response difference reveals whether the Space exists."],
		selectors: [stableSelectors.screenSpaceOverview],
	},
	{
		id: "F03-N07-access-revoked-while-open",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-SCOPE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner loses Space access while views are open.",
		fixtures: ["rbac", "company", "evidence"],
		fixtureModes: ["scope:revoked-while-open", "scope:stale-cache-cleared"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation: "Active views clear protected snapshots when revocation lands.",
		absenceAssertions: ["No protected content remains readable from stale caches."],
		selectors: [stableSelectors.screenSpaceOverview, stableSelectors.screenTaskList],
	},
	{
		id: "F03-N08-default-channel-archive-blocked-and-restore-race",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F03 flow row",
		obligations: ["US-CHANNELS-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner tries to archive #general and races a Channel restore.",
		fixtures: ["spaces-channels", "company", "evidence"],
		fixtureModes: ["channels:archived-readonly", "channels:restore-conflict"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"The default Channel refuses archive and the restore race resolves to one winner.",
		absenceAssertions: [
			"No archived #general is ever persisted.",
			"No partial restore survives the race.",
		],
		selectors: [stableSelectors.screenChannelDirectory],
	},
	{
		id: "F03-N09-archived-space-readonly-and-restore-race",
		flow: "F03",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: US-SPACE-01 row (archived read-only/restore)",
		obligations: ["US-SPACE-01"],
		actors: ["Marek / Owner"],
		permissionState: "Owner opens an archived Space and races its restore.",
		fixtures: ["company", "clock", "evidence"],
		fixtureModes: ["space:archived-readonly", "space:restore-conflict"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"The archived Space presents an explicit read-only state and restore resolves to one winner.",
		absenceAssertions: [
			"No mutation lands on the archived Space.",
			"No partial restore is persisted.",
		],
		selectors: [stableSelectors.screenSpaceOverview],
	},
	{
		id: "F04-P01-structured-mention-to-result",
		flow: "F04",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-THREAD-01", "US-RUN-LIVE-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member mentions the activated Agent via the structured composer.",
		fixtures: ["auth", "company", "queue", "rbac", "clock", "evidence"],
		fixtureModes: ["run-live:submitted", "run-live:terminal-result"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation:
			"Exactly one Message, Mention, Thread, work request, Run, and result exist; the result is a separate attributable Agent Message and never instant.",
		absenceAssertions: [
			"No result is fabricated inline with the request Message.",
			"No second Run spawns from the single structured Mention.",
		],
		selectors: [
			stableSelectors.screenChannelThread,
			stableSelectors.chatComposer,
			stableSelectors.messageRunCard,
		],
	},
	{
		id: "F04-P02-run-card-timing-states",
		flow: "F04",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-RUN-LIVE-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member watches a live Run they requested.",
		fixtures: ["queue", "clock", "company", "evidence"],
		fixtureModes: ["run-live:queued", "run-live:evaluating", "run-live:working"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The run card holds a fixed height across queued, evaluating, and working with realistic elapsed time.",
		absenceAssertions: ["No layout shift occurs as timing states advance."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F04-P03-reconnect-during-run",
		flow: "F04",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-RUN-LIVE-01", "US-QUERY-REALTIME-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member reconnects while their Run is in flight.",
		fixtures: ["realtime-gap", "queue", "company", "evidence"],
		fixtureModes: ["run-live:reconnecting"],
		layer: "realtime",
		serverRequirement: "real-http",
		positiveObservation:
			"The run card resumes truthful state after the transport gap without losing the Run.",
		absenceAssertions: ["No duplicate run card appears after reconnect."],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F04-P04-long-structured-result-card",
		flow: "F04",
		kind: "positive",
		source:
			"week-1-end-to-end-scenarios: US-THREAD-01/US-RUN-LIVE-01 rows (long Markdown, plan/todo/tool summaries)",
		obligations: ["US-THREAD-01", "US-RUN-LIVE-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member reads a long structured Agent result.",
		fixtures: ["company", "queue", "evidence"],
		fixtureModes: ["thread:long-structured-content", "run-live:long-structured-content"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Long Markdown with plan, todo, and tool summaries stays readable inside the bounded card.",
		absenceAssertions: [
			"No unbounded card growth stretches the Thread.",
			"No raw tool dump replaces the summarised sections.",
			"No horizontal page scroll is introduced.",
		],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F04-N01-plain-text-at-name-no-run",
		flow: "F04",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-THREAD-01"],
		actors: ["Lucia / Space Member"],
		permissionState: "Space Member types a plain-text @name without the structured mention.",
		fixtures: ["company", "queue", "evidence"],
		fixtureModes: [],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation: "The Message posts as ordinary text in the Thread.",
		absenceAssertions: ["No Run is created from ordinary text."],
		selectors: [stableSelectors.chatComposer, stableSelectors.screenChannelThread],
	},
	{
		id: "F04-N02-inactive-or-unavailable-agent-mention",
		flow: "F04",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-THREAD-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member mentions an inactive or unavailable Agent.",
		fixtures: ["company", "queue", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"The gate is explained in the Thread and nothing dispatches; capacity-deadline semantics are delegated to F10.",
		absenceAssertions: ["No work request or Run dispatches to the inactive Agent."],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F04-N03-duplicate-delivery-single-run",
		flow: "F04",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-THREAD-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState:
			"Space Member's single structured Mention is delivered twice by the dispatcher.",
		fixtures: ["duplicate-delivery", "queue", "company", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Dispatcher retry and duplicate projection still yield one Run and one result.",
		absenceAssertions: [
			"No additional Run starts from the duplicate delivery.",
			"No second result Message is projected.",
		],
		selectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
	},
	{
		id: "F04-N04-revoked-access-before-projection",
		flow: "F04",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F04 flow row",
		obligations: ["US-SCOPE-01"],
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		permissionState: "Space Member loses anchor access before the result projects.",
		fixtures: ["rbac", "company", "queue", "evidence"],
		fixtureModes: ["scope:revoked-while-open"],
		layer: "http",
		serverRequirement: "real-http",
		positiveObservation: "Projection rechecks anchor access at delivery time.",
		absenceAssertions: ["No result content is disclosed to the revoked member."],
		selectors: [stableSelectors.screenChannelThread],
	},
	{
		id: "F05-P01-typed-assignment-dispatches-once",
		flow: "F05",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Space Lead assigns the activated Agent to a Task.",
		fixtures: ["company", "queue", "clock", "rbac", "evidence"],
		fixtureModes: ["assignment:pending", "assignment:acknowledged"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "One immutable assignment event keys exactly one work request and Run.",
		absenceAssertions: ["No second event or Run derives from the single assignment."],
		selectors: [stableSelectors.screenTaskDetail, stableSelectors.taskAssigneeTrigger],
	},
	{
		id: "F05-P02-run-result-in-task-thread",
		flow: "F05",
		kind: "positive",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-RUN-LIVE-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Space Lead watches the assignee acknowledgement and later result.",
		fixtures: ["queue", "clock", "company", "evidence"],
		fixtureModes: ["run-live:terminal-result"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation:
			"Assignee acknowledgement is distinct from the delayed Agent work result in the Task thread.",
		absenceAssertions: ["No instant fake result replaces the delayed Agent Message."],
		selectors: [stableSelectors.messageRunCard],
	},
	{
		id: "F05-N01-unrelated-save-no-run",
		flow: "F05",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead"],
		permissionState: "Space Lead saves unrelated Task fields with the Agent already assigned.",
		fixtures: ["company", "evidence"],
		fixtureModes: ["assignment:unrelated-save"],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "The unrelated save persists without emitting any assignment event.",
		absenceAssertions: ["No Run starts from a save that does not change the assignee."],
		selectors: [stableSelectors.screenTaskDetail],
	},
	{
		id: "F05-N02-duplicate-delivery-one-event",
		flow: "F05",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Space Lead's committed assignment event is delivered twice.",
		fixtures: ["duplicate-delivery", "queue", "company", "evidence"],
		fixtureModes: ["assignment:duplicate-delivery"],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation:
			"Replayed delivery of the one assignment event still yields a single request and Run.",
		absenceAssertions: ["No duplicate Run or acknowledgement is produced by redelivery."],
		selectors: [stableSelectors.screenTaskDetail],
	},
	{
		id: "F05-N03-same-actor-reassign-no-new-event",
		flow: "F05",
		kind: "negative",
		source:
			"prove-f05-one-agent-assignment-event: assigning the same Actor without a new event starts no Run",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Space Lead re-selects the already assigned Agent.",
		fixtures: ["company", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "Re-assigning the same Actor records no new assignment event.",
		absenceAssertions: ["No new Run starts from the same-actor reassign."],
		selectors: [stableSelectors.screenTaskDetail, stableSelectors.taskAssigneeTrigger],
	},
	{
		id: "F05-N04-active-transfer-fencing",
		flow: "F05",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Space Lead transfers the Task while the Agent Run is active.",
		fixtures: ["company", "queue", "clock", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "real-database",
		positiveObservation: "Transfer is fenced to wait or cancel-and-transfer only.",
		absenceAssertions: ["No overlapping second Run starts while the first is active."],
		selectors: [stableSelectors.screenTaskDetail],
	},
	{
		id: "F05-N05-assignment-error-preserves-intent",
		flow: "F05",
		kind: "negative",
		source: "week-1-end-to-end-scenarios: F05 flow row",
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead"],
		permissionState: "Space Lead's assignment submit fails as a typed mutation error.",
		fixtures: ["company", "evidence"],
		fixtureModes: ["assignment:mutation-error"],
		layer: "browser",
		serverRequirement: "fixture-double",
		positiveObservation: "The failed assignment preserves the Lead's intent for an explicit retry.",
		absenceAssertions: ["No Agent authority is inherited from the assigner on failure."],
		selectors: [stableSelectors.screenTaskDetail, stableSelectors.taskAssigneeTrigger],
	},
	{
		id: "F05-N06-revoked-authority-at-dispatch",
		flow: "F05",
		kind: "negative",
		source: 'prove-f05-one-agent-assignment-event: acceptance "revoked-authority cases"',
		obligations: ["US-TASK-ASSIGN-01"],
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		permissionState: "Assignment authority is revoked between event commit and dispatch.",
		fixtures: ["company", "queue", "rbac", "evidence"],
		fixtureModes: [],
		layer: "integration",
		serverRequirement: "fixture-double",
		positiveObservation: "Dispatch fails safe and the failure stays attributable on the Task.",
		absenceAssertions: ["No Run executes under revoked authority."],
		selectors: [stableSelectors.screenTaskDetail, stableSelectors.messageRunCard],
	},
] as const satisfies readonly Phase0ScenarioCase[];
