import { z } from 'zod'

/**
 * Reference kinds describe where the artifact content lives.
 * - file: repo-relative or absolute path on the worker machine (not publicly accessible)
 * - url: external URL (may or may not be public — depends on the service that generated it)
 * - inline: short text stored directly in ref_value (diffs, summaries, test counts)
 *
 * IMPORTANT: A "url" artifact is NOT automatically publicly shared.
 * It is a reference to wherever the content lives — could be an internal staging URL,
 * a webhook receipt, or a public deployment. The artifact model does not imply public access.
 */
export const ArtifactRefKindSchema = z.enum([
	'file',
	'url',
	'inline',
])

/** Artifact kinds describe what the artifact represents. */
export const ArtifactKindSchema = z.enum([
	'changed_file',
	'diff_summary',
	'test_report',
	'doc',
	'external_receipt',
	'preview_file',
	'preview_url',
	'implementation_prompt',
	'validation_report',
	'other',
])

/** An artifact produced by a run — compact reference, not a blob. */
export const ArtifactSchema = z.object({
	/** Unique artifact ID (generated by orchestrator). */
	id: z.string().optional(),
	/** What the artifact represents. */
	kind: ArtifactKindSchema,
	/** Human-readable label. */
	title: z.string(),
	/** How to locate the content. */
	ref_kind: ArtifactRefKindSchema,
	/** The reference value: file path, URL, or short inline text. */
	ref_value: z.string(),
	/** Optional MIME type hint. */
	mime_type: z.string().optional(),
	/** Optional metadata JSON. */
	metadata: z.record(z.unknown()).optional(),
})

/** Artifacts reported by the worker in run completion.
 *  `kind` accepts any string — the orchestrator normalizes unknown values to "other". */
export const RunArtifactSchema = z.object({
	kind: z.string().default('changed_file'),
	title: z.string(),
	ref_kind: ArtifactRefKindSchema.default('file'),
	ref_value: z.string(),
	mime_type: z.string().optional(),
	metadata: z.record(z.unknown()).optional(),
})
