export { ceoPrompt } from './ceo'
export { strategistPrompt } from './strategist'
export { plannerPrompt } from './planner'
export { developerPrompt } from './developer'
export { reviewerPrompt } from './reviewer'
export { devopsPrompt } from './devops'
export { marketingPrompt } from './marketing'
export { designPrompt } from './design'
export type { AgentRole, PromptContext, PromptTemplate } from './types'
