import { stableSelectors as selector } from "../contracts";
import { aiStateObligations } from "./ai-obligations";
import { phase0QueryStateCoverage } from "./query-coverage";
import type { StateObligation } from "./types";

const queryStateObligations = [
	{
		id: "US-AUTH-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: [],
		selectors: [selector.screenSignIn],
		fixtureModeIds: [
			"auth:session-resolving",
			"auth:anonymous-redirect",
			"auth:session-revoked",
			"auth:credential-pending",
			"auth:recoverable-error",
		],
		layers: ["http", "browser"],
		absenceAssertion:
			"Protected content never flashes and redirects cannot loop or escape the safe destination.",
	},
	{
		id: "US-INVITE-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: [],
		selectors: [selector.screenInvitationAcceptance],
		fixtureModeIds: [
			"invitation:eligible",
			"invitation:expired",
			"invitation:revoked",
			"invitation:already-used",
			"invitation:wrong-account",
			"invitation:superseded-by-resend",
			"invitation:accept-resend-race",
			"invitation:query-error",
			"invitation:mutation-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No raw token, duplicate Actor, identity merge, widened binding, or second acceptance receipt is exposed.",
	},
	{
		id: "US-SETUP-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: [],
		selectors: [selector.screenCompanySetup, selector.screenTeamSetup, selector.screenWorkSetup],
		fixtureModeIds: [
			"setup:initial-loading",
			"setup:new-company",
			"setup:resumable-partial",
			"setup:version-conflict",
			"setup:mutation-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No second Company graph, lost input, stale overwrite, provider requirement, or premature success is possible.",
	},
	{
		id: "US-HOME-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: [],
		selectors: [selector.screenCompanyHome],
		fixtureModeIds: ["home:loading", "home:empty-human-only", "home:populated", "home:error"],
		layers: ["http", "browser"],
		absenceAssertion:
			"No false empty state, stale protected content, hidden primary action, overflow, or fake Agent activity appears.",
	},
	{
		id: "US-ACTIVITY-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: [],
		selectors: [selector.screenCompanyActivity],
		fixtureModeIds: [
			"activity:loading",
			"activity:empty",
			"activity:filtered-empty",
			"activity:populated",
			"activity:error",
		],
		layers: ["http", "browser"],
		absenceAssertion:
			"No fixture-only or duplicate event, unauthorized subject disclosure, or transport event masquerades as activity.",
	},
	{
		id: "US-SPACES-01",
		ownerFlow: "F01",
		proofTask: "prove-f01-human-only-company-bootstrap",
		reusedBy: ["F03"],
		selectors: [selector.screenSpaceDirectory],
		fixtureModeIds: [
			"spaces:loading",
			"spaces:whole-company-only",
			"spaces:filtered-empty",
			"spaces:query-error",
			"spaces:archive-conflict",
			"spaces:restore-conflict",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No hidden Whole Company, unauthorized row or count, duplicate slug, partial restore, or lost draft is possible.",
	},
	{
		id: "US-SPACE-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: [],
		selectors: [selector.screenSpaceOverview],
		fixtureModeIds: [
			"space:loading",
			"space:empty-sections",
			"space:query-error",
			"space:archived-readonly",
			"space:version-conflict",
			"space:mutation-error",
			"space:restore-conflict",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No cross-Space row, existence oracle, partial restore, stale protected content, or layout overflow appears.",
	},
	{
		id: "US-PROJECT-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: [],
		selectors: [selector.screenProjectContext],
		fixtureModeIds: [
			"project:loading",
			"project:optional-absent",
			"project:query-error",
			"project:archived",
			"project:version-conflict",
			"project:mutation-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No Project-owned membership, cross-Space link, orphaned object, existence oracle, or replaced Space navigation occurs.",
	},
	{
		id: "US-CHANNELS-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: [],
		selectors: [selector.screenChannelDirectory],
		fixtureModeIds: [
			"channels:loading",
			"channels:archived-filter-empty",
			"channels:query-error",
			"channels:archived-readonly",
			"channels:restore-conflict",
			"channels:slug-conflict",
			"channels:create-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No cross-Space general alias, local duplicate slug, default-Channel archive, or lost draft is possible.",
	},
	{
		id: "US-GOAL-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: [],
		selectors: [selector.screenGoalList, selector.screenGoalDetail, selector.goalCriterionRow],
		fixtureModeIds: [
			"goal:loading",
			"goal:empty-list",
			"goal:filtered-empty",
			"goal:query-error",
			"goal:archived-readonly",
			"goal:version-conflict",
			"goal:mutation-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No cross-Space Goal, stale overwrite, partial Criterion write, Task-count progress, or existence disclosure occurs.",
	},
	{
		id: "US-TASK-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: ["F05"],
		selectors: [selector.screenTaskList, selector.screenTaskDetail],
		fixtureModeIds: [
			"task:loading",
			"task:empty-list",
			"task:filtered-empty",
			"task:query-error",
			"task:archived-readonly",
			"task:version-conflict",
			"task:mutation-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No cross-Space or cyclic relation, stale overwrite, partial mutation, lost draft, or existence disclosure occurs.",
	},
	{
		id: "US-TASK-ASSIGN-01",
		ownerFlow: "F05",
		proofTask: "prove-f05-one-agent-assignment-event",
		reusedBy: [],
		selectors: [selector.screenTaskDetail, selector.taskAssigneeTrigger, selector.messageRunCard],
		fixtureModeIds: [
			"assignment:pending",
			"assignment:acknowledged",
			"assignment:mutation-error",
			"assignment:duplicate-delivery",
			"assignment:unrelated-save",
		],
		layers: ["integration", "browser"],
		absenceAssertion:
			"No duplicate assignment event or Run, lost assignee intent, or inherited Agent authority is possible.",
	},
	{
		id: "US-THREAD-01",
		ownerFlow: "F04",
		proofTask: "prove-f04-structured-mention-to-attributable-result",
		reusedBy: ["F09"],
		selectors: [selector.screenChannelThread, selector.chatComposer],
		fixtureModeIds: [
			"thread:history-loading",
			"thread:empty",
			"thread:query-error",
			"thread:archived-readonly",
			"thread:send-error",
			"thread:long-structured-content",
		],
		layers: ["http", "integration", "browser", "realtime"],
		absenceAssertion:
			"No bubble-only rendering, cross-Space content, lost draft, duplicate work/result, or stale protected content appears.",
	},
	{
		id: "US-NEEDS-01",
		ownerFlow: "F06",
		proofTask: "prove-f06-exact-run-permission-decision",
		reusedBy: [],
		selectors: [selector.screenNeedsYou],
		fixtureModeIds: [
			"needs:loading",
			"needs:empty",
			"needs:actionable",
			"needs:error",
			"needs:configuration-only",
			"needs:stale-decision",
			"needs:decision-error",
		],
		layers: ["http", "integration", "browser"],
		absenceAssertion:
			"No recipient-as-authority shortcut, hidden no-approver state, unauthorized decision, duplicate row, or existence leak occurs.",
	},
	{
		id: "US-RUN-DETAIL-01",
		ownerFlow: "F06",
		proofTask: "prove-f06-exact-run-permission-decision",
		reusedBy: ["F07"],
		selectors: [selector.screenRunDetail],
		fixtureModeIds: [
			"run-detail:loading",
			"run-detail:empty-activity",
			"run-detail:query-error",
			"run-detail:revoked",
			"run-detail:terminal-history",
			"run-detail:stale-command",
			"run-detail:command-error",
		],
		layers: ["http", "integration", "browser", "realtime"],
		absenceAssertion:
			"No raw provider or tool leak, existence oracle, reopened attempt, erased effect, or transient-only truth occurs.",
	},
	{
		id: "US-SCOPE-01",
		ownerFlow: "F03",
		proofTask: "prove-f03-space-project-goal-and-task-creation",
		reusedBy: ["F01", "F02", "F04", "F05", "F06", "F07", "F08", "F09", "F10"],
		selectors: phase0QueryStateCoverage.map((surface) => surface.selector),
		fixtureModeIds: [
			"scope:not-found",
			"scope:denied",
			"scope:revoked-while-open",
			"scope:stale-cache-cleared",
		],
		layers: ["contract", "http", "browser"],
		absenceAssertion:
			"No id, count, title, timing, stale-cache, or Company-to-Space existence oracle can be observed.",
	},
	{
		id: "US-QUERY-REALTIME-01",
		ownerFlow: "F09",
		proofTask: "prove-f09-realtime-gap-recovery-without-duplicates",
		reusedBy: ["F01", "F02", "F03", "F04", "F05", "F06", "F07", "F08", "F10"],
		selectors: [
			selector.screenCompanyHome,
			selector.screenCompanyActivity,
			selector.screenAiSetup,
			selector.screenSpaceDirectory,
			selector.screenSpaceOverview,
			selector.screenProjectContext,
			selector.screenChannelDirectory,
			selector.screenGoalList,
			selector.screenGoalDetail,
			selector.screenTaskList,
			selector.screenTaskDetail,
			selector.screenChannelThread,
			selector.screenNeedsYou,
			selector.screenRunDetail,
		],
		fixtureModeIds: [
			"realtime:disconnect",
			"realtime:bounded-replay",
			"realtime:replay-gap",
			"realtime:access-revoked",
		],
		layers: ["http", "integration", "browser", "realtime"],
		absenceAssertion:
			"No blank-slate flash, duplicate entity, unread regression, stale unauthorized content, or transport-owned business truth occurs.",
	},
] as const satisfies readonly StateObligation[];

export const stateObligationRegistry = [
	...queryStateObligations,
	...aiStateObligations,
] as const satisfies readonly StateObligation[];
