export { program } from './program'

import './commands/init'
import './commands/status'
import './commands/ask'
import './commands/tasks'
import './commands/agents'
import './commands/inbox'
import './commands/attach'
import './commands/start'
import './commands/secrets'
import './commands/knowledge'
import './commands/board'
import './commands/chat'
import './commands/channels'
import './commands/artifacts'
import './commands/approve'
import './commands/reject'
import './commands/dashboard'
import './commands/auth'
import './commands/git'
