export const COMPANY_ROLE_PERMISSIONS = {
	owner: [
		"company.read",
		"company.update",
		"company.transfer_ownership",
		"members.read",
		"members.invite_suspend",
		"roles.read",
		"roles.manage",
		"providers.read",
		"providers.connect_verify_rotate_revoke",
		"work_machines.read",
		"work_machines.manage",
		"spaces.create_archive",
		"audit.read",
	],
	admin: [
		"company.read",
		"company.update",
		"members.read",
		"members.invite_suspend",
		"roles.read",
		"providers.read",
		"providers.connect_verify_rotate_revoke",
		"work_machines.read",
		"work_machines.manage",
		"spaces.create_archive",
		"audit.read",
	],
	member: ["company.read", "members.read"],
} as const;

export const SPACE_ROLE_PERMISSIONS = {
	lead: [
		"space.read",
		"space.update",
		"space.members.manage",
		"projects.create_update_archive",
		"goals.create_update",
		"goals.assess_criteria",
		"goals.request_review",
		"goals.review_achieve_reopen",
		"tasks.create_update_assign_transition",
		"tasks.review",
		"chat.read",
		"chat.write",
		"chat.manage",
		"runs.request",
		"runs.read_cancel_retry",
		"runs.steer",
		"runs.approve_effect",
		"knowledge.read",
		"knowledge.draft",
		"knowledge.publish_archive",
	],
	member: [
		"space.read",
		"projects.create_update_archive",
		"goals.create_update",
		"goals.assess_criteria",
		"goals.request_review",
		"tasks.create_update_assign_transition",
		"chat.read",
		"chat.write",
		"runs.request",
		"runs.read_cancel_retry",
		"runs.steer",
		"runs.approve_effect",
		"knowledge.read",
		"knowledge.draft",
	],
	viewer: ["space.read", "chat.read", "knowledge.read"],
} as const;

export const FIXED_ROLE_DEFINITIONS = [
	{
		systemKey: "owner",
		name: "Company Owner",
		scopeType: "company",
		permissions: COMPANY_ROLE_PERMISSIONS.owner,
	},
	{
		systemKey: "admin",
		name: "Company Admin",
		scopeType: "company",
		permissions: COMPANY_ROLE_PERMISSIONS.admin,
	},
	{
		systemKey: "member",
		name: "Company Member",
		scopeType: "company",
		permissions: COMPANY_ROLE_PERMISSIONS.member,
	},
	{
		systemKey: "lead",
		name: "Space Lead",
		scopeType: "space",
		permissions: SPACE_ROLE_PERMISSIONS.lead,
	},
	{
		systemKey: "space-member",
		name: "Space Member",
		scopeType: "space",
		permissions: SPACE_ROLE_PERMISSIONS.member,
	},
	{
		systemKey: "viewer",
		name: "Space Viewer",
		scopeType: "space",
		permissions: SPACE_ROLE_PERMISSIONS.viewer,
	},
] as const;
