import type { Phase0ScenarioContract } from "../harness";

export const stableSelectors = {
	screenSignIn: "screen-sign-in",
	screenCompanySetup: "screen-company-setup",
	screenTeamSetup: "screen-team-setup",
	screenWorkSetup: "screen-work-setup",
	screenInvitationAcceptance: "screen-invitation-acceptance",
	screenCompanyHome: "screen-company-home",
	screenCompanyActivity: "screen-company-activity",
	screenAiSetup: "screen-ai-setup",
	screenSpaceDirectory: "screen-space-directory",
	screenSpaceOverview: "screen-space-overview",
	screenProjectContext: "screen-project-context",
	screenChannelDirectory: "screen-channel-directory",
	screenGoalList: "screen-goal-list",
	screenGoalDetail: "screen-goal-detail",
	screenTaskList: "screen-task-list",
	screenTaskDetail: "screen-task-detail",
	screenChannelThread: "screen-channel-thread",
	screenNeedsYou: "screen-needs-you",
	screenRunDetail: "screen-run-detail",
	providerVerifyAction: "provider-verify-action",
	agentActivateAction: "agent-activate-action",
	goalCriterionRow: "goal-criterion-row",
	taskAssigneeTrigger: "task-assignee-trigger",
	chatComposer: "chat-composer",
	messageRunCard: "message-run-card",
	permissionDecisionApprove: "permission-decision-approve",
	permissionDecisionDeny: "permission-decision-deny",
	permissionRoutingState: "permission-routing-state",
	runCancelAction: "run-cancel-action",
	runRetryAction: "run-retry-action",
	realtimeState: "realtime-state",
} as const;

export const phase0ScenarioContracts = [
	{
		flow: "F01",
		useCase: "UC-P0-001",
		slug: "bootstrap-human-only-company",
		actors: ["Marek / Owner", "Lucia / invited Human"],
		fixtures: ["auth", "clock", "company", "evidence", "invitations", "rbac", "screen-states"],
		layers: ["http", "integration", "browser"],
		stableSelectors: [
			stableSelectors.screenSignIn,
			stableSelectors.screenCompanySetup,
			stableSelectors.screenTeamSetup,
			stableSelectors.screenWorkSetup,
			stableSelectors.screenInvitationAcceptance,
			stableSelectors.screenCompanyHome,
			stableSelectors.screenCompanyActivity,
			stableSelectors.screenSpaceDirectory,
			stableSelectors.screenSpaceOverview,
			stableSelectors.screenChannelThread,
			stableSelectors.chatComposer,
		],
		negativeOracle:
			"No provider secret or Run is created; invalid invitation and resend races create no duplicate Actor or widened access.",
		requiresRealHttp: true,
	},
	{
		flow: "F02",
		useCase: "UC-P0-002",
		slug: "activate-autopilot-commercial-provider",
		actors: ["Tomáš / Admin", "Autopilot / Agent"],
		fixtures: ["auth", "clock", "company", "evidence", "provider", "rbac"],
		layers: ["http", "integration", "browser"],
		stableSelectors: [
			stableSelectors.screenAiSetup,
			stableSelectors.providerVerifyAction,
			stableSelectors.agentActivateAction,
		],
		negativeOracle: "Invalid, stale, model-less, or capacity-less setup cannot activate the Agent.",
		requiresRealHttp: true,
	},
	{
		flow: "F03",
		useCase: "UC-P0-003",
		slug: "create-space-project-goal-tasks",
		actors: ["Marek / Owner"],
		fixtures: ["auth", "clock", "company", "evidence", "rbac", "spaces-channels"],
		layers: ["http", "integration", "browser"],
		stableSelectors: [
			stableSelectors.screenSpaceDirectory,
			stableSelectors.screenSpaceOverview,
			stableSelectors.screenProjectContext,
			stableSelectors.screenChannelDirectory,
			stableSelectors.screenChannelThread,
			stableSelectors.screenGoalList,
			stableSelectors.screenGoalDetail,
			stableSelectors.goalCriterionRow,
			stableSelectors.screenTaskList,
			stableSelectors.screenTaskDetail,
			stableSelectors.taskAssigneeTrigger,
		],
		negativeOracle:
			"Same-leaf Channels stay Space-anchored; local slug conflicts and cross-Space Message, query, relation, or move are rejected without partial writes.",
		requiresRealHttp: true,
	},
	{
		flow: "F04",
		useCase: "UC-P0-004",
		slug: "mention-agent-and-project-result",
		actors: ["Lucia / Space Member", "Autopilot / Agent"],
		fixtures: [
			"auth",
			"clock",
			"company",
			"duplicate-delivery",
			"evidence",
			"queue",
			"rbac",
			"realtime-gap",
		],
		layers: ["http", "integration", "browser", "realtime"],
		stableSelectors: [
			stableSelectors.screenChannelThread,
			stableSelectors.chatComposer,
			stableSelectors.messageRunCard,
		],
		negativeOracle: "Text-only or duplicate Mention delivery starts no additional Run.",
		requiresRealHttp: true,
	},
	{
		flow: "F05",
		useCase: "UC-P0-005",
		slug: "assign-agent-once",
		actors: ["Marek / Space Lead", "Autopilot / Agent"],
		fixtures: ["clock", "company", "duplicate-delivery", "evidence", "queue", "rbac"],
		layers: ["integration", "browser"],
		stableSelectors: [
			stableSelectors.screenTaskDetail,
			stableSelectors.taskAssigneeTrigger,
			stableSelectors.messageRunCard,
		],
		negativeOracle: "Unrelated Task saves and assignment-event replay start no Run.",
		requiresRealHttp: false,
	},
	{
		flow: "F06",
		useCase: "UC-P0-006",
		slug: "request-run-permission",
		actors: ["Autopilot / Agent", "Marek / authorized approver"],
		fixtures: ["auth", "clock", "company", "evidence", "permissions", "queue", "rbac"],
		layers: ["http", "integration", "browser"],
		stableSelectors: [
			stableSelectors.screenNeedsYou,
			stableSelectors.screenRunDetail,
			stableSelectors.permissionDecisionApprove,
			stableSelectors.permissionDecisionDeny,
			stableSelectors.permissionRoutingState,
		],
		negativeOracle:
			"Wrong or configuration-only approver, no-approver routing, expired request, duplicate decision, and unknown effect remain denied without widening another Run.",
		requiresRealHttp: true,
	},
	{
		flow: "F07",
		useCase: "UC-P0-007",
		slug: "cancel-and-retry-run",
		actors: ["Lucia / requester", "Marek / Space Lead", "Autopilot / Agent"],
		fixtures: ["clock", "company", "duplicate-delivery", "evidence", "queue", "rbac"],
		layers: ["integration", "browser"],
		stableSelectors: [
			stableSelectors.screenRunDetail,
			stableSelectors.runCancelAction,
			stableSelectors.runRetryAction,
		],
		negativeOracle: "A terminal attempt is immutable and retry creates a linked attempt.",
		requiresRealHttp: false,
	},
	{
		flow: "F08",
		useCase: "UC-P0-008",
		slug: "delegate-between-agents-safely",
		actors: ["Autopilot / Agent", "Architect / Agent", "Critic / Agent"],
		fixtures: [
			"activated-agents",
			"clock",
			"company",
			"duplicate-delivery",
			"evidence",
			"queue",
			"rbac",
		],
		layers: ["integration", "browser"],
		stableSelectors: [stableSelectors.screenChannelThread, stableSelectors.messageRunCard],
		negativeOracle:
			"Inactive or incompatible Agent, missing membership, depth above three, repeated lineage fingerprint, and sibling lifecycle coupling are rejected.",
		requiresRealHttp: false,
	},
	{
		flow: "F09",
		useCase: "UC-P0-009",
		slug: "recover-realtime-gap",
		actors: ["Lucia / Space Member"],
		fixtures: ["auth", "clock", "company", "duplicate-delivery", "evidence", "realtime-gap"],
		layers: ["http", "integration", "browser", "realtime"],
		stableSelectors: [stableSelectors.screenChannelThread, stableSelectors.realtimeState],
		negativeOracle: "Replay-gap recovery creates no duplicate Message, work request, or Run.",
		requiresRealHttp: true,
	},
	{
		flow: "F10",
		useCase: "UC-P0-010",
		slug: "handle-provider-or-capacity-loss",
		actors: ["Tomáš / Admin", "Lucia / requester"],
		fixtures: ["clock", "company", "evidence", "provider", "queue", "rbac"],
		layers: ["integration", "browser"],
		stableSelectors: [stableSelectors.screenAiSetup, stableSelectors.messageRunCard],
		negativeOracle: "No fallback model, fake Run, or fake success is selected.",
		requiresRealHttp: false,
	},
] as const satisfies readonly Phase0ScenarioContract[];
